C ----------------------------------------------------------------------
C     - SUBROUTINE MEMORIA
C ----------------------------------------------------------------------
	SUBROUTINE MEMORIA(Ris)
      INTEGER*2 Numero
	INCLUDE 'General.fi'
	INCLUDE 'Ris.for'
	TYPE(Risultati)::Ris,Ris1
	TYPE(Risultati),STATIC::MEM(40)
	IF(NOUTP3.LE.39)THEN
	   MEM(NOUTP3)=Ris
         Ris1%Indice=0
         MEM(NOUTP3+1)=Ris1 
	ENDIF
	RETURN
	ENTRY RECUPERA(Ris,Numero)
!DEC$ ATTRIBUTES DLLEXPORT::RECUPERA
	IF(Numero.LE.40)THEN
	   Ris=MEM(Numero)
	ENDIF
	RETURN
	END
C ----------------------------------------------------------------------
C     - SUBROUTINE SELVA - 54
C ----------------------------------------------------------------------
      SUBROUTINE SELVA(STREAM,STAMPA,FIRMA,ID,ARCH)
!DEC$ ATTRIBUTES DLLEXPORT::/SYSTEM/,SELVA,/CFIRMA/
      TYPE SCHEDE
	   CHARACTER*80 SK(100)
	END TYPE
	TYPE BUFFER
	   CHARACTER*40 STAMPA
      END TYPE
	TYPE(SCHEDE)::STREAM
	TYPE(BUFFER)::STAMPA,FIRMA,ARCH
	INTEGER*2 ID
	INCLUDE 'GENERAL.FI'
	COMMON/CFIRMA/FIRMAAZ
	CHARACTER*26 FIRMAAZ
	INTEGER*2 CS,NCALC,IND
	IDEBUG=ID
	FIRMAAZ=FIRMA%STAMPA
      NCALC=0
      NSTOP=0
      NUOVER=0
	NOUTP3=0
	IO=3
      OPEN(IO,FILE=STAMPA%STAMPA)
	CS=1
    1 NDOS=0
c  per NDOS vedi CONDEN
      CALL INPUT(IND,STREAM,CS,ARCH)
	WRITE(IO,1001)
      IF(IND.LT.1.OR.IND.GT.36)GOTO40
      IF(IND-32) 5,5,10
    5 CALL PROC1(IND)
      GO TO 35
   10 IF(IND-34) 15,15,20
   15 CALL PROC2(IND)
      GO TO 35
   20 IF(IND-36) 25,25,40
   25 CALL PROC3(IND)
   35 NCALC=NCALC+1
      IF(NCALC-50) 1,1,40
   40 CLOSE(IO)
      RETURN
 1001 FORMAT(1H*)
      END
C ----------------------------------------------------------------------
C     - SUBROUTINE INPUT - 82
C ----------------------------------------------------------------------
      SUBROUTINE INPUT(IND,STREAM,CS,ARCH)
      INTEGER*2 IND,CS
	TYPE SCHEDE
	   CHARACTER*80 SK(100)
	END TYPE
	TYPE BUFFER
	   CHARACTER*40 Str
      END TYPE
	TYPE(SCHEDE)::STREAM
	TYPE(BUFFER)::ARCH
C      REAL LAMDA,MU,NU,LAMDA0,MU0,NU0
	INTEGER*2 ISTLIB
C	CHARACTER*4 NAME
C      COMMON/OPTION/KAPPA(50,50),KIJ,KEQ,IM,ISUP,KCRT,KWRT,VL,ICAL
C      COMMON/NCODEX/NCOD(50),NAME(50,5),NCST,NCNST,NCIP,NC,NCW
C      COMMON/BANK1/M(50),TC(50),PC(50),ZC(50),OMEGA(50),BP(50)
C      COMMON/BANK2/ZRA(50),SPG(50),TD(50),PD(50)
C      COMMON/SYSTEM/IN,IO,KDOS,MDOS,LDOS,NDOS,NUOVER,NOUTP3,KCONV,IDEBUG
C      COMMON/INDEX/KBDF,KE,KU,KHS,KW
C      COMMON/TEMPRE/TINP,PINP,T,P
      INCLUDE 'GENERAL.FI'
	INCLUDE 'TITLE.FI'
C      COMMON/TITLE/TIT(18),IUF,IUM,IUP,INDI,FTM,WTF,HFT,QT,SFT,AFHS(3,4)
      INCLUDE 'HYPOT.FI'
C	COMMON/HYPOT/KINh,KFIN,A1H(50),A2H(50),A3H(50),UOPK(50),API(50)
	INCLUDE 'DETTAGLI.FI'
C      COMMON/HFASE/HF,Q,HL,HV,DPHL,DPHV,DTHL,DTHV,DXHL(50),DYHV(50)
C      COMMON/SFASE/SF,SL,SV,DPSL,DPSV,DTSL,DTSV,DXSL(50),DYSV(50)
C      COMMON/CHCURV/NP,IDT,DT,IDP,DP,TSET(50),PSET(50)
C      COMMON/SPECIF/AL(50),AV(50),BL(50),BV(50),Cspec,Dspec,Espec
	INCLUDE 'SOLUZ.FI'
C      COMMON/MOLFR/X(50),Y(50),Z(50),ZN(50,2),SOM(2)
C      COMMON/STOPPA/NSTOP,NPAGE,NCALC
C      COMMON/K00K/ITER,IHOL,KIDL,K006
C      COMMON/PARTIZ/LAMDA,MU,NU,YW
C	REAL LAMDA,MU,NU
C      COMMON/RATIO/LAMDA0,MU0,NU0
C	REAL LAMDA0,MU0,NU0
      COMMON/KAPID/AKID(50)
	REAL AKID
C      COMMON/HYDROG/INDH2
C     COMMON/INDICE/INMIL
C-----------------------------------------------------
      REAL VALCOS(10),DT,DP,SOMMA
	INTEGER*2 IND1(10),IND2(10),IDCOMP(10),IDCOST(10)
	INTEGER*2 KSP,I,J,ICAL,INMIL,IPREC,IH,IS,IDT,IDP
	INTEGER*2 II,JJ,L,Kloc
      CHARACTER*1 AB(5),BLANK,WAT1,WAT(4)
      CHARACTER*4 BB
C-----------------------------------------------------
C *** FINE MODIFICA
      DATA AB/'W','A','B','C','D'/,BLANK/' '/,BB/'    '/
	IF(IDEBUG.GE.1)WRITE(IO,195)IND,CS
      ISUP=0
      KCRT=0
      KSP=0
      KW=0
      NP=1
      NCNST=0
      READ(STREAM%SK(CS),100) (TIT(I),I=1,4),
     *(TIT(I),I=6,10),
     *(TIT(I),I=12,18),INDI,(WAT(J),J=1,4),ISETK,ICAL,ISTLIB,INMIL
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
	IF(TIT(1).EQ.'FINE')THEN
	  IND=0
	  RETURN
	ENDIF
	CS=CS+1
      TIT(5)=BB
      TIT(11)=BB
      IF(NSTOP.GT.0.AND.ICAL.GT.1) GO TO 200
      IND=INDI
c      IF(INDI.EQ.0)GOTO200
      DO 1 I=1,4
      IF(WAT(I).EQ.BLANK) GO TO 1
      WAT1=WAT(I)
      GO TO 2
    1 CONTINUE
      GO TO 4
    2 DO 3 I=1,5
      IF(WAT1.NE.AB(I)) GO TO 3
      KW=I
      GO TO 4
    3 CONTINUE
    4 CONTINUE
      IF(IND.GE.18.AND.IND.LE.24) KSP=1
      IF(ICAL.GT.0) GO TO 8
C SK2
      READ(STREAM%SK(CS),110) NCW,NCIP,IUM,KEQ,IM,KIJ,KWRT,KCRT,ITER,
     1	IPREC,IHOL,KIDL,K006,INDH2
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
	CS=CS+1
c      RHOL=IHOL
      NC=NCW
      IF(KW.NE.0) NC=NC-1
      NCST=NCW-NCIP-NCNST
      KEQ=KEQ+1
      KCRT=KCRT+1
      VL=1.E-4
      IF(IPREC) 8,8,5
    5 GO TO(6,7),IPREC
    6 VL=VL*0.1
      GO TO 8
    7 VL=VL*10.
    8 CONTINUE
C SK3
      READ(STREAM%SK(CS),120)  FTM,IUF,TSET(1),PSET(1),IUP,LAMDA,NU,
	1MU,HFT,IH,QT,SFT,IS
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
	CS=CS+1
      IF(NSTOP) 10,10,9
    9 IF(IH.NE.0.OR.IS.NE.0) GO TO 200
      NSTOP=0
   10 CONTINUE
      LAMDA0=LAMDA
      MU0=MU
      NU0=NU
      IF(IND.LT.35) GO TO 20
CSK4
      READ(STREAM%SK(CS),170) NP,IDT,DT,IDP,DP
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
	CS=CS+1
      DT=ABS(DT)
      IF(IDT) 14,14,13
   13 DO 133 II=2,NP,9
      JJ=II+8
	IF(JJ.GT.NP)JJ=NP
CSK5
      READ(STREAM%SK(CS),180) (TSET(I),I=II,JJ)
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
  133 CS=CS+1
      GO TO 16
   14 IF(IND.EQ.36) DT=-DT
      DO 15 I=2,NP
   15 TSET(I)=TSET(I-1)+DT
   16 IF(IDP) 18,18,17
   17 DO 177 II=2,NP,9
      JJ=II+8
	IF(JJ.GT.NP)JJ=NP
CSK6
      READ(STREAM%SK(CS),180) (PSET(I),I=II,JJ)
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
  177 CS=CS+1
      GO TO 20
   18 DO 19 I=2,NP
   19 PSET(I)=PSET(I-1)+DP
   20 DO 24 I=1,NP
      IF(IUM) 21,21,22
   21 TSET(I)=TSET(I)+273.15
      PSET(I)=PSET(I)/1.033
      GO TO 23
   22 TSET(I)=(TSET(I)+459.67)/1.8
      PSET(I)=PSET(I)/14.696
   23 IF(IUP.EQ.0) PSET(I)=PSET(I)+1.
   24 CONTINUE
      T=TSET(1)
      P=PSET(1)
      TINP=T
      PINP=P
      DO 30 I=1,NCW
      AV(I)=0.
      AL(I)=0.
      BV(I)=0.
   30 BL(I)=0.
      Cspec=0.
      Dspec=0.
      Espec=0.
      IF(KSP.EQ.0)GO TO 42
CSK7
      READ(STREAM%SK(CS),190) Espec,Dspec,Cspec,KSP
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
	CS=CS+1
	DO 301 II=1,KSP,4
	JJ=II+3
	IF(JJ.GT.KSP)JJ=KSP
CSK8
      READ(STREAM%SK(CS),140) (IDCOST(I),IDCOMP(I),VALCOS(I),I=II,JJ)
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
  301	CS=CS+1
      DO 40 L=1,KSP
      Kloc=IDCOST(L)
      I=IDCOMP(L)
      GO TO(32,34,36,38),Kloc
   32 AL(I)=VALCOS(L)
      GO TO 40
   34 AV(I)=VALCOS(L)
      GO TO 40
   36 BL(I)=VALCOS(L)
      GO TO 40
   38 BV(I)=VALCOS(L)
   40 CONTINUE
   42 IF(ICAL) 44,44,43
   43 IF(KIDL.EQ.2) KIDL=0
      GO TO(84,70,75,80),ICAL
   44 DO 46 J=1,NCW
      DO 46 I=1,NCW
   46 KAPPA(I,J)=0.
      IF(KIJ.EQ.0)GO TO 447
	DO 466 II=1,KIJ,4
	JJ=II+3
	IF(JJ.GT.KIJ)JJ=KIJ
CSK9 COSTANTI BINARIE
      READ(STREAM%SK(CS),130) (IND1(I),IND2(I),KAPPA(IND1(I),IND2(I)),
	1I=II,JJ)
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
  466	CS=CS+1
      DO 300 I=1,NCW
      DO 300 J=1,NCW
      IF(KAPPA(I,J).NE.0) KAPPA(J,I)=KAPPA(I,J)
  300 CONTINUE
  447	DO 47 II=1,NCW,5
	JJ=II+4
	IF(JJ.GT.NCW)JJ=NCW
CSK10
      READ(STREAM%SK(CS),150) (NCOD(I),Z(I),I=II,JJ)
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
   47 CS=CS+1
      CALL NORMAL(Z,NCW)
      IF(ISETK.GT.0)CALL SETK(ARCH)
      CALL LETBAN(ISTLIB.EQ.1)
      IF(NCIP.EQ.0)GO TO 51
      KINh=NCST+NCNST
      IF(KW.EQ.0)KINh=KINh+1
      KFIN=KINh-1+NCIP
      DO 49 I=KINh,KFIN
CSK11
      READ(STREAM%SK(CS),160) (NAME(I,J),J=1,4),BP(I),API(I),M(I),
	1SPG(I),TC(I),PC(I),OMEGA(I)
	IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
	CS=CS+1
   49 NAME(I,5)=BB
      CALL IPOTET
   51 IF(KIDL.NE.0) THEN
        DO 511 II=1,NC,9
	    JJ=II+8
	    IF(JJ.GT.NC)JJ=NC
CSK12
	    IF(IDEBUG.GE.2)WRITE(IO,196)CS,STREAM%SK(CS)
          READ(STREAM%SK(CS),180) (AKID(I),I=II,JJ)
  511	  CS=CS+1
      ENDIF
      IF(IUF) 59,59,53
   53 SOMMA=0.
      DO 55 I=1,NCW
   55 SOMMA=SOMMA+Z(I)/M(I)
      DO 57 I=1,NCW
   57 Z(I)=(Z(I)/M(I))/SOMMA
   59 WTF=0.
      DO 61 I=1,NCW
   61 WTF=WTF+Z(I)*M(I)
      IF(IUF) 90,90,63
   63 FTM=FTM/WTF
      GO TO 90
   70 DO 72 I=1,NCW
   72 Z(I)=Y(I)
      GO TO 83
   75 IF(NCOD(NCW)-72) 81,77,81
   77 NCW=NC
      KW=0
      GO TO 81
   80 Z(NCW)=X(NCW+1)
   81 DO 82 I=1,NC
   82 Z(I)=X(I)
   83 CALL NORMAL(Z,NCW)
   84 WTF=0.
      DO 85 I=1,NCW
   85 WTF=WTF+M(I)*Z(I)
      FTM =AFHS(1,ICAL)
      IF(IH.EQ.0.AND.IS.EQ.0) GO TO 90
      IF(IH.NE.0)  HFT=AFHS(2,ICAL)
      IF(IS.NE.0)  SFT=AFHS(3,ICAL)
   90 CONTINUE
      DO 91 I=1,NCW
      IF(Z(I).EQ.0.) Z(I)=1.E-14
   91 CONTINUE
      HF=HFT/FTM
      Q=QT/FTM
      SF=SFT/FTM
      IF(IUM) 95,95,92
   92 HF=HF/1.8
      Q=Q/1.8
   95 CONTINUE
      IF(IDEBUG.GE.1)WRITE(IO,198)
      RETURN
  100 FORMAT(4A4,2A3,3A4,2A4,A2,4A4,I4,4A1,4I1)
  110 FORMAT(I7,I6,11I5,I4)
  120 FORMAT(E10.0,I1,F6.0,E10.0,I1,3F5.0,E10.0,I1,E10.0,E10.0,I1)
  130 FORMAT(4(2I5,F6.0))
  140 FORMAT(4(2I4,F8.0))
  150 FORMAT(5(I4,E10.0))
  160 FORMAT(4A4,7E8.0)
  170 FORMAT(2I5,F5.0,I5,F5.0)
  180 FORMAT(9F8.0)
  190 FORMAT(3F7.0,I5)
  195 FORMAT(' *** SUBROUTINE INPUT *** Entrata.    IND=',I5,';CS=',I5)
  196 FORMAT(T5,'222 SUBROUTINE INPUT 222 Scheda n°',I3,'. ',
     1A80) 
c  197 FORMAT('                          Scheda di input n°',I3/
c     11X,A80) 
  198 FORMAT(' *** SUBROUTINE INPUT *** Uscita')
  200 IND=0
      RETURN
      END
C ----------------------------------------------------------------------
C     - SUBROUTINE SETK
C ----------------------------------------------------------------------
      SUBROUTINE SETK(ARCH)
	TYPE BUFFER
	   CHARACTER*40 Str
      END TYPE
	TYPE(BUFFER)::ARCH
	INCLUDE 'GENERAL.FI'
C------------------------------------------
	CHARACTER*50 PERCFILE
	CHARACTER*10 FILE
	CHARACTER*40 ARCHD
	CHARACTER*2 NUMERO
	LOGICAL ESISTE
	INTEGER*4 IERR
	INTEGER*2 I,J,II,JJ,SK
	REAL COST
C------------------------------------------
	IF(IDEBUG.GE.1)WRITE(IO,3000)
	SELECT CASE(IEQ)
	CASE(1)
	FILE='RKS'
	CASE(2)
	FILE='PR'
	END SELECT
	ARCHD=ARCH%Str
	WRITE(NUMERO,'(I2)')ISETK
	IF(ISETK.LT.10)NUMERO(1:1)='0'
	FILE='\'//FILE(1:LEN_TRIM(FILE))//NUMERO//'.DAT'
	PERCFILE=ARCHD(1:LEN_TRIM(ARCHD))//FILE
	INQUIRE(FILE=PERCFILE,EXIST=ESISTE)
	IF(.NOT.ESISTE)THEN
	   WRITE(IO,2000)PERCFILE
	   RETURN
	ENDIF
	OPEN(90,FILE=PERCFILE,STATUS='OLD',MODE='READ',IOSTAT=IERR,
     *    ERR=1000)
	SK=1
    1	READ(90,2500,END=2,ERR=1010,IOSTAT=IERR)I,J,COST
      IF(I.EQ.999.OR.J.EQ.999)GOTO 2
	SK=SK+1
	IF(I.EQ.0.OR.J.EQ.0)GOTO 1
	DO 10 II=1,NCW
	IF(NCOD(II).EQ.I)THEN
	   DO 11 JJ=1,NCW
	   IF(NCOD(JJ).EQ.J)THEN
	     IF(IDEBUG.GE.2)WRITE(IO,3010)I,J,COST
		 IF(COST.NE.0.)THEN
		    KIJ=KIJ+1
		    KAPPA(II,JJ)=COST
		    KAPPA(JJ,II)=COST
	     ENDIF
		 GOTO 1 
	   ENDIF
   11    CONTINUE
	ENDIF
   10 CONTINUE
	GOTO 1 
    2 CLOSE(90)
	RETURN
 1000 WRITE(IO,2010)IERR,PERCFILE
	RETURN
 1010 WRITE(IO,2020)IERR,SK,PERCFILE
      RETURN
 2000 FORMAT(' - BEWARE: CANNOT FIND LIBRARY FILE ',A40)
 2010 FORMAT(' - BEWARE: ERROR NUMBER',I5,' WHILE OPENING ',A40) 
 2020 FORMAT(' - BEWARE: ERROR NUMBER',I5,' WHILE READING SK n°',
     1    I2,' ON FILE ',A40)
 2500 FORMAT(2I3,F5.4)
 3000 FORMAT(T5,'222 SETK 222. Etrata')
 3010 FORMAT(T5,'222 SETK 222. Costante applicabile. I,J,COST=',
     *2I3,F10.4)
	END
C ----------------------------------------------------------------------
C     - SUBROUTINE PROC2 - 55
C ----------------------------------------------------------------------
      SUBROUTINE PROC2(IND)
	INTEGER*2 IND
c	CHARACTER*4 NAME
c      COMMON/SYSTEM/IN,IO,KDOS,MDOS,LDOS,NDOS,NUOVER,NOUTP3,KCONV,IDEBUG
c      COMMON/NCODEX/NCOD(50),NAME(50,5),NCST,NCNST,NCIP,NC,NCW
c      COMMON/TEMPRE/TINP,PINP,T,P
c      COMMON/INDEX/KBDF,KE,KU,KHS,KW
      INCLUDE 'GENERAL.FI'
	INCLUDE 'DETTAGLI.FI'
C      COMMON/KVALUE/DTK(50),DPK(50),DXK(50,50),DYK(50,50),K(50)
C	REAL K
	INCLUDE 'SOLUZ.FI'
C      COMMON/MOLFR/X(50),Y(50),Z(50),ZN(50,2),SOM(2)
C      COMMON/PARTIZ/LAMDA,MU,NU,YW
C      REAL LAMDA,MU,NU
C      COMMON/DENSLV/ROL,ROV,TPCL,TPCV,PPCL,PPCV,IROL
C---------------------------------------------
	INTEGER*2 IW,ISTP,I
C---------------------------------------------
      IF(IDEBUG.EQ.1)WRITE(IO,1100)IND
      MU=0.
      IW=0
      ISTP=0
      DO 1 I=1,NCW
      X(I)=0.
      K(I)=0.
    1 Y(I)=0.
      KHS=3
      KE=5
      KU=4
   21 KBDF=IABS(IND)-32                        !22/06/01
      GO TO (5,20), KBDF
    5 LAMDA=0.
      DO 10 I=1,NC
   10 X(I)=Z(I)
      IF(KW.EQ.0) GO TO 15
      MU=Z(NCW)
      IW=1
   15 NU=1.-LAMDA-MU
      CALL PROP(1,1,1,0,KW,1,1)
      GO TO 30
   20 DO 25 I=1,NCW
   25 Y(I)=Z(I)
      LAMDA=1.
      NU=1.-LAMDA-MU
      CALL PROP(2,2,0,1,0,1,0)
   30 CONTINUE
      IF(IND.LT.0)THEN                        !22/06/01
	   IF(KBDF.EQ.1.AND.T.GT.TPCL)IND=34    !22/06/01
	   IF(KBDF.EQ.2.AND.T.LT.TPCV)IND=33    !22/06/01
         IF(IND.GT.0)GOTO 21                  !22/06/01
	ENDIF                                   !22/06/01
      CALL OUTPUT(IND,IW,ISTP)
      IF(IDEBUG.EQ.1)WRITE(IO,1110)IND
      RETURN
 1100 FORMAT(' *** SUBROUTINE PROC2 *** Entrata. IND=',I5) 
 1110 FORMAT(' *** SUBROUTINE PROC2 *** Uscita.  IND=',I5) 
      END
C ----------------------------------------------------------------------
C     - SUBROUTINE PROC3 - 16
C ----------------------------------------------------------------------
      SUBROUTINE PROC3(IND)
	INTEGER*2 IND
	INCLUDE 'GENERAL.FI'
	INCLUDE 'TITLE.FI'
C      COMMON/TITLE/TIT(18),IUF,IUM,IUP,INDI,FTM,WTF,HFT,QT,SFT,AFHS(3,4)
	INCLUDE 'SOLUZ.FI'
C      COMMON/CHCURV/NP,IDT,DT,IDP,DP,TT(50),PP(50)
c      COMMON/SYSTEM/IN,IO,KDOS,MDOS,LDOS,NDOS,NUOVER,NOUTP3,KCONV,IDEBUG
C-----------------------------------------
      CHARACTER*4 A1(2),A2(3),BLK
	INTEGER*2 IK,I,KK,JK,ICONT
C-----------------------------------------
      DATA A1/'HEAT','COOL'/,A2/'ING ','CURV','E   '/,IK/15/,BLK/'    '/
      IF(IDEBUG.GE.1)WRITE(IO,1100)IND
      DO 55 I=15,18
C*****MODIFICA FBM-HI
CM    IF(TIT(I)-BLK) 60,55,60
      IF(TIT(I).NE.BLK) GOTO 60
   55 CONTINUE
      KK=IND-34
      TIT(IK)=A1(KK)
      DO 50 JK=1,3
C*****MODIFICA FBM-HI
      ICONT=IK+JK
CM 50 TIT(IK+JK)=A2(JK)
   50 TIT(ICONT)=A2(JK)
   60 I=0
      IF(IND-35) 1,1,25
    1 IF(IDTT) 15,15,5
    5 I=I+1
      IF(NP-I) 15,15,10
   10 IF(TT(I).LT.TT(I+1)) GO TO 5
      GO TO 20
   15 CALL EVAPOR
      IF(IDEBUG.GE.1)WRITE(IO,1110)
      RETURN
   20 WRITE(IO,100)
      WRITE(IO,105)
      IF(IDEBUG.GE.1)WRITE(IO,1110)
      RETURN
   25 IF(IDTT) 40,40,30
   30 I=I+1
      IF(NP-I) 40,40,35
   35 IF(TT(I).GT.TT(I+1)) GO TO 30
      GO TO 45
   40 CALL CONDEN
      IF(IDEBUG.GE.1)WRITE(IO,1110)
      RETURN
   45 WRITE(IO,100)
      WRITE(IO,110)
      IF(IDEBUG.GE.1)WRITE(IO,1110)
      RETURN
  100 FORMAT(' ****** BEWARE: ERROR IN INPUT CARDS',/)
  105 FORMAT(' - THE TEMPERATURES ASSIGNED ARE NOT INCREASING')
  110 FORMAT(' - THE TEMPERATURES ASSIGNED ARE NOT DECREASING')
 1100 FORMAT(' *** SUBROUTINE PROC3 *** Entrata.   IND=',I5) 
 1110 FORMAT(' *** SUBROUTINE PROC3 *** Uscita.') 
      END
      SUBROUTINE PRNUOVER
!DEC$ ATTRIBUTES DLLEXPORT::PRNUOVER
	INCLUDE 'TITLE.FI'
C      CHARACTER*4 TIT
C      COMMON/TITLE/TIT(18),IUF,IUM,IUP,INDI,FTM,WTF,HFT,QT,SFT,AFHS(3,4)
	INCLUDE 'GENERAL.FI'
C      COMMON/SYSTEM/IN,IO,KDOS,MDOS,LDOS,NDOS,NUOVER,NOUTP3,KCONV
C--------------------------------------
C--------------------------------------
      GOTO(1,2,3,4,5),NUOVER+1
    1	IF(INDI.GT.0.AND.INDI.LT.37)RETURN
      WRITE(IO,999)INDI
      RETURN
    2 WRITE(IO,1000)NUOVER
      RETURN
    3 WRITE(IO,1000)NUOVER
      RETURN
    4 WRITE(IO,1000)NUOVER
      RETURN
    5 WRITE(IO,1000)NUOVER
      RETURN
    6 WRITE(IO,1000)NUOVER
      RETURN
  999 FORMAT(' - CALCULATION CODE INVALID ('I3')')
 1000 FORMAT(' - DIVERGENCE IN SOAVEH. CODE 'I3)
      END

