	TYPE Risultati
	   REAL Temperatura
 	   REAL Pressione
	   REAL VapMolFraction
	   REAL VapMasFraction
	   REAL Entalpie(5)
	   REAL Entropie(5)
	   REAL PesiMol(3)
	   REAL Density(2)
	   REAL TCrit(2)
	   REAL PCrit(2)
	   REAL CpGas
	   REAL CvGas
	   REAL SurfTens
	   REAL Visco(2)
	   REAL Conduc(2)
	   REAL CompressF(2)
	   REAL HAcqLiq
	   REAL MolAcqLiq
	   REAL MasAcqLiq
	   INTEGER*2 kConv
	   INTEGER*2 Indice
	END TYPE
