'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ventil.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property fmt5_101() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fmt5_101", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property fmt5_102() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fmt5_102", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il gruppo di items da montare su ventilatore a comune non è stato definito correttamente..
        '''</summary>
        Friend ReadOnly Property str1011() As String
            Get
                Return ResourceManager.GetString("str1011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;item o il gruppo di items da smontare non sono stati definiti correttamente.
        '''</summary>
        Friend ReadOnly Property str1021() As String
            Get
                Return ResourceManager.GetString("str1021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gli items da montare su ventilatore comune non sono in sequenza.
        '''</summary>
        Friend ReadOnly Property str1030() As String
            Get
                Return ResourceManager.GetString("str1030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è stata definita la struttura della Commessa. Operazione impossibile.
        '''</summary>
        Friend ReadOnly Property str1032() As String
            Get
                Return ResourceManager.GetString("str1032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è sato definito correttamente il numero di Commessa. Operazione terminata..
        '''</summary>
        Friend ReadOnly Property str1034() As String
            Get
                Return ResourceManager.GetString("str1034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Questo item appartiene ad un banco|per il quale non è stata definita la Commessa.
        '''</summary>
        Friend ReadOnly Property str1035() As String
            Get
                Return ResourceManager.GetString("str1035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è stato impostata la Distinta Base per questo Item..
        '''</summary>
        Friend ReadOnly Property str1036() As String
            Get
                Return ResourceManager.GetString("str1036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Questo item non è stato dimensionato meccanicamente.
        '''</summary>
        Friend ReadOnly Property str1038() As String
            Get
                Return ResourceManager.GetString("str1038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il progetto non è stato compattato. Operazione impossibile..
        '''</summary>
        Friend ReadOnly Property str1040() As String
            Get
                Return ResourceManager.GetString("str1040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I dati da elaborare per la generazione|del file testate_/telai e dello scantling|per l&apos;Item &amp; rischiano di non|essere aggiornati.Vuoi procedere comunque con il file?.
        '''</summary>
        Friend ReadOnly Property str1041() As String
            Get
                Return ResourceManager.GetString("str1041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esiste già il file testate/telai |per l&apos;item &amp; dis. &amp;).|Vuoi utilizzarlo ?.
        '''</summary>
        Friend ReadOnly Property str1042() As String
            Get
                Return ResourceManager.GetString("str1042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base Dati PRV non valida o nessun item definito..
        '''</summary>
        Friend ReadOnly Property str1070() As String
            Get
                Return ResourceManager.GetString("str1070", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selezionare prima un oggetto nel|pannello di visualizzazione struttura.
        '''</summary>
        Friend ReadOnly Property str1080() As String
            Get
                Return ResourceManager.GetString("str1080", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spuntare almeno un rapporto di stampa da passare a WinWord.
        '''</summary>
        Friend ReadOnly Property str1090() As String
            Get
                Return ResourceManager.GetString("str1090", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nel caso di DB e scantlings già elaborati è necessario adottare cautele quando si rielabora il sommario..
        '''</summary>
        Friend ReadOnly Property str1095() As String
            Get
                Return ResourceManager.GetString("str1095", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operazione impossibile poiché non vi è alcun item attivo..
        '''</summary>
        Friend ReadOnly Property str1099() As String
            Get
                Return ResourceManager.GetString("str1099", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uno o più dati di input sono errati..
        '''</summary>
        Friend ReadOnly Property str1100() As String
            Get
                Return ResourceManager.GetString("str1100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il calcolo termico non può continuare..
        '''</summary>
        Friend ReadOnly Property str1101() As String
            Get
                Return ResourceManager.GetString("str1101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il calcolo termico non può continuare. (Errore n° ###).
        '''</summary>
        Friend ReadOnly Property str1102() As String
            Get
                Return ResourceManager.GetString("str1102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esiste già una curva di raffreddamento|per questa alternativa (file &amp;).|Vuoi rigenerarla?.
        '''</summary>
        Friend ReadOnly Property str1103() As String
            Get
                Return ResourceManager.GetString("str1103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è possibile calcolare il numero di Prandtl della fase vapore idrocarburica..
        '''</summary>
        Friend ReadOnly Property str1105() As String
            Get
                Return ResourceManager.GetString("str1105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prima di eseguire questa operazione|è necessario definire almeno un&apos;alternativa..
        '''</summary>
        Friend ReadOnly Property str1106() As String
            Get
                Return ResourceManager.GetString("str1106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Efficienza di legamento.
        '''</summary>
        Friend ReadOnly Property str1110() As String
            Get
                Return ResourceManager.GetString("str1110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spessori.
        '''</summary>
        Friend ReadOnly Property str1111() As String
            Get
                Return ResourceManager.GetString("str1111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura di progetto.
        '''</summary>
        Friend ReadOnly Property str1112() As String
            Get
                Return ResourceManager.GetString("str1112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressione di progetto.
        '''</summary>
        Friend ReadOnly Property str1113() As String
            Get
                Return ResourceManager.GetString("str1113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura di esercizio.
        '''</summary>
        Friend ReadOnly Property str1114() As String
            Get
                Return ResourceManager.GetString("str1114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressione di esercizio.
        '''</summary>
        Friend ReadOnly Property str1115() As String
            Get
                Return ResourceManager.GetString("str1115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pressione di prova.
        '''</summary>
        Friend ReadOnly Property str1116() As String
            Get
                Return ResourceManager.GetString("str1116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temperatura minima.
        '''</summary>
        Friend ReadOnly Property str1117() As String
            Get
                Return ResourceManager.GetString("str1117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Splittaggio cassa A.
        '''</summary>
        Friend ReadOnly Property str1118() As String
            Get
                Return ResourceManager.GetString("str1118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Splittaggio cassa B.
        '''</summary>
        Friend ReadOnly Property str1119() As String
            Get
                Return ResourceManager.GetString("str1119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.in/out.
        '''</summary>
        Friend ReadOnly Property str1120() As String
            Get
                Return ResourceManager.GetString("str1120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.ingr..
        '''</summary>
        Friend ReadOnly Property str1121() As String
            Get
                Return ResourceManager.GetString("str1121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.uscita.
        '''</summary>
        Friend ReadOnly Property str1122() As String
            Get
                Return ResourceManager.GetString("str1122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.A sup.
        '''</summary>
        Friend ReadOnly Property str1123() As String
            Get
                Return ResourceManager.GetString("str1123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.A inf.
        '''</summary>
        Friend ReadOnly Property str1124() As String
            Get
                Return ResourceManager.GetString("str1124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.B.
        '''</summary>
        Friend ReadOnly Property str1125() As String
            Get
                Return ResourceManager.GetString("str1125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.A.
        '''</summary>
        Friend ReadOnly Property str1126() As String
            Get
                Return ResourceManager.GetString("str1126", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.B sup.
        '''</summary>
        Friend ReadOnly Property str1127() As String
            Get
                Return ResourceManager.GetString("str1127", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.B inf.
        '''</summary>
        Friend ReadOnly Property str1128() As String
            Get
                Return ResourceManager.GetString("str1128", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.A sup.
        '''</summary>
        Friend ReadOnly Property str1129() As String
            Get
                Return ResourceManager.GetString("str1129", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.A inf.
        '''</summary>
        Friend ReadOnly Property str1130() As String
            Get
                Return ResourceManager.GetString("str1130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.B sup.
        '''</summary>
        Friend ReadOnly Property str1131() As String
            Get
                Return ResourceManager.GetString("str1131", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cas.B inf.
        '''</summary>
        Friend ReadOnly Property str1132() As String
            Get
                Return ResourceManager.GetString("str1132", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N° di tipi di tubi (max 2).
        '''</summary>
        Friend ReadOnly Property str1134() As String
            Get
                Return ResourceManager.GetString("str1134", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N° file con 1. tipo.
        '''</summary>
        Friend ReadOnly Property str1135() As String
            Get
                Return ResourceManager.GetString("str1135", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N° file con 2. tipo.
        '''</summary>
        Friend ReadOnly Property str1136() As String
            Get
                Return ResourceManager.GetString("str1136", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diam. 1. tipo [mm].
        '''</summary>
        Friend ReadOnly Property str1137() As String
            Get
                Return ResourceManager.GetString("str1137", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diam. 2. tipo [mm].
        '''</summary>
        Friend ReadOnly Property str1138() As String
            Get
                Return ResourceManager.GetString("str1138", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spess. 1. tipo [mm].
        '''</summary>
        Friend ReadOnly Property str1139() As String
            Get
                Return ResourceManager.GetString("str1139", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spess. 2. tipo [mm].
        '''</summary>
        Friend ReadOnly Property str1140() As String
            Get
                Return ResourceManager.GetString("str1140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passo vert. 1. tipo [mm].
        '''</summary>
        Friend ReadOnly Property str1141() As String
            Get
                Return ResourceManager.GetString("str1141", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passo vert. 2. tipo [mm].
        '''</summary>
        Friend ReadOnly Property str1142() As String
            Get
                Return ResourceManager.GetString("str1142", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A-515-GR 60         A-516-GR 60         A-515-GR 70         A-516-GR 70        |.
        '''</summary>
        Friend ReadOnly Property str1143() As String
            Get
                Return ResourceManager.GetString("str1143", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  FE35.2-UNI 663      HII-DIN 17155       A 240-304           A 312-TP 304       |.
        '''</summary>
        Friend ReadOnly Property str1144() As String
            Get
                Return ResourceManager.GetString("str1144", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A 240-304L          A 312-TP 304L       A 240-316           A 240-316L         |.
        '''</summary>
        Friend ReadOnly Property str1145() As String
            Get
                Return ResourceManager.GetString("str1145", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  A 240-321           A 106-GR B          ST35.8I-17175       ST35.8II-17175     |.
        '''</summary>
        Friend ReadOnly Property str1146() As String
            Get
                Return ResourceManager.GetString("str1146", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Larghezza gradino   [mm].
        '''</summary>
        Friend ReadOnly Property str1148() As String
            Get
                Return ResourceManager.GetString("str1148", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Larghezza guarniz.  [mm].
        '''</summary>
        Friend ReadOnly Property str1149() As String
            Get
                Return ResourceManager.GetString("str1149", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tolleranza di lav.  [mm].
        '''</summary>
        Friend ReadOnly Property str1150() As String
            Get
                Return ResourceManager.GetString("str1150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Larghezza int.cassa [mm].
        '''</summary>
        Friend ReadOnly Property str1151() As String
            Get
                Return ResourceManager.GetString("str1151", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hg                  [mm].
        '''</summary>
        Friend ReadOnly Property str1152() As String
            Get
                Return ResourceManager.GetString("str1152", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I                   [mm].
        '''</summary>
        Friend ReadOnly Property str1153() As String
            Get
                Return ResourceManager.GetString("str1153", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to x                   [mm].
        '''</summary>
        Friend ReadOnly Property str1154() As String
            Get
                Return ResourceManager.GetString("str1154", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spessore flangia    [mm].
        '''</summary>
        Friend ReadOnly Property str1155() As String
            Get
                Return ResourceManager.GetString("str1155", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spessore top/btm    [mm].
        '''</summary>
        Friend ReadOnly Property str1156() As String
            Get
                Return ResourceManager.GetString("str1156", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desideri verificare le dilatazioni differenziali dei tubi|nella configurazione non splittata ?.
        '''</summary>
        Friend ReadOnly Property str1200() As String
            Get
                Return ResourceManager.GetString("str1200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le casse di ingresso e uscita|saranno uguali? .
        '''</summary>
        Friend ReadOnly Property str1210() As String
            Get
                Return ResourceManager.GetString("str1210", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cassa A singola, B singola.
        '''</summary>
        Friend ReadOnly Property str1240() As String
            Get
                Return ResourceManager.GetString("str1240", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cassa A split,   B singola.
        '''</summary>
        Friend ReadOnly Property str1241() As String
            Get
                Return ResourceManager.GetString("str1241", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cassa A singola, B split.
        '''</summary>
        Friend ReadOnly Property str1242() As String
            Get
                Return ResourceManager.GetString("str1242", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cassa A split,   B split.
        '''</summary>
        Friend ReadOnly Property str1243() As String
            Get
                Return ResourceManager.GetString("str1243", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non e&apos; stato ancora generato il|testate/telai. Alcuni dati sono|quindi da fornire a mano       |.
        '''</summary>
        Friend ReadOnly Property str1244() As String
            Get
                Return ResourceManager.GetString("str1244", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poiché questo item ha un solo|passaggio, questo calcolo non|avrebbe senso.               |.
        '''</summary>
        Friend ReadOnly Property str1245() As String
            Get
                Return ResourceManager.GetString("str1245", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non disponiamo di metodi per|il calcolo delle testate   |di tipo.
        '''</summary>
        Friend ReadOnly Property str1246() As String
            Get
                Return ResourceManager.GetString("str1246", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non disponiamo di metodi per|il calcolo delle testate   |a norme.
        '''</summary>
        Friend ReadOnly Property str1247() As String
            Get
                Return ResourceManager.GetString("str1247", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&apos; stato selezionato un ventilatore|senza aver (ri)eseguito il calcolo termico..
        '''</summary>
        Friend ReadOnly Property str1260() As String
            Get
                Return ResourceManager.GetString("str1260", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il numero della commessa è illegale.
        '''</summary>
        Friend ReadOnly Property str1300() As String
            Get
                Return ResourceManager.GetString("str1300", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non esiste un ventilatore adatto. |Cambiare i dati di progetto..
        '''</summary>
        Friend ReadOnly Property str1313() As String
            Get
                Return ResourceManager.GetString("str1313", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prima di eseguire un calcolo biso-|gna identificare un&apos;alternativa..
        '''</summary>
        Friend ReadOnly Property str1317() As String
            Get
                Return ResourceManager.GetString("str1317", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non hai eseguito il calcolo termico.|Le scelte or ora effettuate verranno|perse..
        '''</summary>
        Friend ReadOnly Property str1320() As String
            Get
                Return ResourceManager.GetString("str1320", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non hai scelto il ventilatore,      |ovvero la scelta va rieseguita.     |Le scelte or ora potrebbero non es- |sere corrette..
        '''</summary>
        Friend ReadOnly Property str1321() As String
            Get
                Return ResourceManager.GetString("str1321", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è stata trovata la directory \COFIMCO |del programma MEGAC.  Il file dei    |dati (.SVI) non è stato generato..
        '''</summary>
        Friend ReadOnly Property str1335() As String
            Get
                Return ResourceManager.GetString("str1335", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è stata trovata la directory \MOORE   |del programma MFL.    Il file dei    |dati        non è stato generato..
        '''</summary>
        Friend ReadOnly Property str1336() As String
            Get
                Return ResourceManager.GetString("str1336", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è stata trovata la directory \CF |del programma CF-P15. Il file dei    |dati (.INV) è stato comunque salvato..
        '''</summary>
        Friend ReadOnly Property str1337() As String
            Get
                Return ResourceManager.GetString("str1337", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non e&apos; stato scelto un ventilatore|in modo valido : prego rifare..
        '''</summary>
        Friend ReadOnly Property str1339() As String
            Get
                Return ResourceManager.GetString("str1339", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Errore durante un&apos;operazione sul file &amp;. |(&amp;)..
        '''</summary>
        Friend ReadOnly Property str800() As String
            Get
                Return ResourceManager.GetString("str800", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
