'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class aa
    Inherits DataSet
    
    Private tableListaMat As ListaMatDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("ListaMat")) Is Nothing) Then
                Me.Tables.Add(New ListaMatDataTable(ds.Tables("ListaMat")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property ListaMat As ListaMatDataTable
        Get
            Return Me.tableListaMat
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As aa = CType(MyBase.Clone,aa)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("ListaMat")) Is Nothing) Then
            Me.Tables.Add(New ListaMatDataTable(ds.Tables("ListaMat")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableListaMat = CType(Me.Tables("ListaMat"),ListaMatDataTable)
        If (Not (Me.tableListaMat) Is Nothing) Then
            Me.tableListaMat.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "aa"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/aa.xsd"
        Me.Locale = New System.Globalization.CultureInfo("it-IT")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableListaMat = New ListaMatDataTable
        Me.Tables.Add(Me.tableListaMat)
    End Sub
    
    Private Function ShouldSerializeListaMat() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub ListaMatRowChangeEventHandler(ByVal sender As Object, ByVal e As ListaMatRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ListaMatDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnAlfaCod As DataColumn
        
        Private columnAlloyUNS As DataColumn
        
        Private columnCaract1 As DataColumn
        
        Private columnCaract2 As DataColumn
        
        Private columnCaract3 As DataColumn
        
        Private columnCaract4 As DataColumn
        
        Private columnCAT As DataColumn
        
        Private columnClassCondTemp As DataColumn
        
        Private columnClasse As DataColumn
        
        Private columnCMT As DataColumn
        
        Private columnComposiz As DataColumn
        
        Private columnConducTer As DataColumn
        
        Private columnCT As DataColumn
        
        Private columnDescription As DataColumn
        
        Private columnElasCod As DataColumn
        
        Private columnID As DataColumn
        
        Private columnInd As DataColumn
        
        Private columnMat As DataColumn
        
        Private columnMatGroup As DataColumn
        
        Private columnmatId As DataColumn
        
        Private columnNomeComm As DataColumn
        
        Private columnNotes As DataColumn
        
        Private columnNotes2 As DataColumn
        
        Private columnObsoleto As DataColumn
        
        Private columnOrdinamento As DataColumn
        
        Private columnP1A As DataColumn
        
        Private columnP1B As DataColumn
        
        Private columnP2A As DataColumn
        
        Private columnP2B As DataColumn
        
        Private columnP3 As DataColumn
        
        Private columnP4 As DataColumn
        
        Private columnProduct As DataColumn
        
        Private columnPSP As DataColumn
        
        Private columnPU As DataColumn
        
        Private columnPU2 As DataColumn
        
        Private columnPY1 As DataColumn
        
        Private columnPY3 As DataColumn
        
        Private columnR1A As DataColumn
        
        Private columnR1B As DataColumn
        
        Private columnR2A As DataColumn
        
        Private columnR2B As DataColumn
        
        Private columnR3 As DataColumn
        
        Private columnR4 As DataColumn
        
        Private columnRU As DataColumn
        
        Private columnRU2 As DataColumn
        
        Private columnRY1 As DataColumn
        
        Private columnRY3 As DataColumn
        
        Private columnSizeThk As DataColumn
        
        Private columnSpec As DataColumn
        
        Private columnTypeGrade As DataColumn
        
        Private columnVolta As DataColumn
        
        Friend Sub New()
            MyBase.New("ListaMat")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property AlfaCodColumn As DataColumn
            Get
                Return Me.columnAlfaCod
            End Get
        End Property
        
        Friend ReadOnly Property AlloyUNSColumn As DataColumn
            Get
                Return Me.columnAlloyUNS
            End Get
        End Property
        
        Friend ReadOnly Property Caract1Column As DataColumn
            Get
                Return Me.columnCaract1
            End Get
        End Property
        
        Friend ReadOnly Property Caract2Column As DataColumn
            Get
                Return Me.columnCaract2
            End Get
        End Property
        
        Friend ReadOnly Property Caract3Column As DataColumn
            Get
                Return Me.columnCaract3
            End Get
        End Property
        
        Friend ReadOnly Property Caract4Column As DataColumn
            Get
                Return Me.columnCaract4
            End Get
        End Property
        
        Friend ReadOnly Property CATColumn As DataColumn
            Get
                Return Me.columnCAT
            End Get
        End Property
        
        Friend ReadOnly Property ClassCondTempColumn As DataColumn
            Get
                Return Me.columnClassCondTemp
            End Get
        End Property
        
        Friend ReadOnly Property ClasseColumn As DataColumn
            Get
                Return Me.columnClasse
            End Get
        End Property
        
        Friend ReadOnly Property CMTColumn As DataColumn
            Get
                Return Me.columnCMT
            End Get
        End Property
        
        Friend ReadOnly Property ComposizColumn As DataColumn
            Get
                Return Me.columnComposiz
            End Get
        End Property
        
        Friend ReadOnly Property ConducTerColumn As DataColumn
            Get
                Return Me.columnConducTer
            End Get
        End Property
        
        Friend ReadOnly Property CTColumn As DataColumn
            Get
                Return Me.columnCT
            End Get
        End Property
        
        Friend ReadOnly Property DescriptionColumn As DataColumn
            Get
                Return Me.columnDescription
            End Get
        End Property
        
        Friend ReadOnly Property ElasCodColumn As DataColumn
            Get
                Return Me.columnElasCod
            End Get
        End Property
        
        Friend ReadOnly Property IDColumn As DataColumn
            Get
                Return Me.columnID
            End Get
        End Property
        
        Friend ReadOnly Property IndColumn As DataColumn
            Get
                Return Me.columnInd
            End Get
        End Property
        
        Friend ReadOnly Property MatColumn As DataColumn
            Get
                Return Me.columnMat
            End Get
        End Property
        
        Friend ReadOnly Property MatGroupColumn As DataColumn
            Get
                Return Me.columnMatGroup
            End Get
        End Property
        
        Friend ReadOnly Property matIdColumn As DataColumn
            Get
                Return Me.columnmatId
            End Get
        End Property
        
        Friend ReadOnly Property NomeCommColumn As DataColumn
            Get
                Return Me.columnNomeComm
            End Get
        End Property
        
        Friend ReadOnly Property NotesColumn As DataColumn
            Get
                Return Me.columnNotes
            End Get
        End Property
        
        Friend ReadOnly Property Notes2Column As DataColumn
            Get
                Return Me.columnNotes2
            End Get
        End Property
        
        Friend ReadOnly Property ObsoletoColumn As DataColumn
            Get
                Return Me.columnObsoleto
            End Get
        End Property
        
        Friend ReadOnly Property OrdinamentoColumn As DataColumn
            Get
                Return Me.columnOrdinamento
            End Get
        End Property
        
        Friend ReadOnly Property P1AColumn As DataColumn
            Get
                Return Me.columnP1A
            End Get
        End Property
        
        Friend ReadOnly Property P1BColumn As DataColumn
            Get
                Return Me.columnP1B
            End Get
        End Property
        
        Friend ReadOnly Property P2AColumn As DataColumn
            Get
                Return Me.columnP2A
            End Get
        End Property
        
        Friend ReadOnly Property P2BColumn As DataColumn
            Get
                Return Me.columnP2B
            End Get
        End Property
        
        Friend ReadOnly Property P3Column As DataColumn
            Get
                Return Me.columnP3
            End Get
        End Property
        
        Friend ReadOnly Property P4Column As DataColumn
            Get
                Return Me.columnP4
            End Get
        End Property
        
        Friend ReadOnly Property ProductColumn As DataColumn
            Get
                Return Me.columnProduct
            End Get
        End Property
        
        Friend ReadOnly Property PSPColumn As DataColumn
            Get
                Return Me.columnPSP
            End Get
        End Property
        
        Friend ReadOnly Property PUColumn As DataColumn
            Get
                Return Me.columnPU
            End Get
        End Property
        
        Friend ReadOnly Property PU2Column As DataColumn
            Get
                Return Me.columnPU2
            End Get
        End Property
        
        Friend ReadOnly Property PY1Column As DataColumn
            Get
                Return Me.columnPY1
            End Get
        End Property
        
        Friend ReadOnly Property PY3Column As DataColumn
            Get
                Return Me.columnPY3
            End Get
        End Property
        
        Friend ReadOnly Property R1AColumn As DataColumn
            Get
                Return Me.columnR1A
            End Get
        End Property
        
        Friend ReadOnly Property R1BColumn As DataColumn
            Get
                Return Me.columnR1B
            End Get
        End Property
        
        Friend ReadOnly Property R2AColumn As DataColumn
            Get
                Return Me.columnR2A
            End Get
        End Property
        
        Friend ReadOnly Property R2BColumn As DataColumn
            Get
                Return Me.columnR2B
            End Get
        End Property
        
        Friend ReadOnly Property R3Column As DataColumn
            Get
                Return Me.columnR3
            End Get
        End Property
        
        Friend ReadOnly Property R4Column As DataColumn
            Get
                Return Me.columnR4
            End Get
        End Property
        
        Friend ReadOnly Property RUColumn As DataColumn
            Get
                Return Me.columnRU
            End Get
        End Property
        
        Friend ReadOnly Property RU2Column As DataColumn
            Get
                Return Me.columnRU2
            End Get
        End Property
        
        Friend ReadOnly Property RY1Column As DataColumn
            Get
                Return Me.columnRY1
            End Get
        End Property
        
        Friend ReadOnly Property RY3Column As DataColumn
            Get
                Return Me.columnRY3
            End Get
        End Property
        
        Friend ReadOnly Property SizeThkColumn As DataColumn
            Get
                Return Me.columnSizeThk
            End Get
        End Property
        
        Friend ReadOnly Property SpecColumn As DataColumn
            Get
                Return Me.columnSpec
            End Get
        End Property
        
        Friend ReadOnly Property TypeGradeColumn As DataColumn
            Get
                Return Me.columnTypeGrade
            End Get
        End Property
        
        Friend ReadOnly Property VoltaColumn As DataColumn
            Get
                Return Me.columnVolta
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As ListaMatRow
            Get
                Return CType(Me.Rows(index),ListaMatRow)
            End Get
        End Property
        
        Public Event ListaMatRowChanged As ListaMatRowChangeEventHandler
        
        Public Event ListaMatRowChanging As ListaMatRowChangeEventHandler
        
        Public Event ListaMatRowDeleted As ListaMatRowChangeEventHandler
        
        Public Event ListaMatRowDeleting As ListaMatRowChangeEventHandler
        
        Public Overloads Sub AddListaMatRow(ByVal row As ListaMatRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddListaMatRow( _
                    ByVal AlfaCod As Short,  _
                    ByVal AlloyUNS As String,  _
                    ByVal Caract1 As Integer,  _
                    ByVal Caract2 As Integer,  _
                    ByVal Caract3 As Integer,  _
                    ByVal Caract4 As Integer,  _
                    ByVal CAT As String,  _
                    ByVal ClassCondTemp As String,  _
                    ByVal Classe As Short,  _
                    ByVal CMT As String,  _
                    ByVal Composiz As String,  _
                    ByVal ConducTer As Short,  _
                    ByVal CT As String,  _
                    ByVal Description As String,  _
                    ByVal ElasCod As Short,  _
                    ByVal Ind As Short,  _
                    ByVal Mat As String,  _
                    ByVal MatGroup As Short,  _
                    ByVal matId As String,  _
                    ByVal NomeComm As String,  _
                    ByVal Notes As String,  _
                    ByVal Notes2 As String,  _
                    ByVal Obsoleto As Boolean,  _
                    ByVal Ordinamento As Single,  _
                    ByVal P1A As String,  _
                    ByVal P1B As String,  _
                    ByVal P2A As String,  _
                    ByVal P2B As String,  _
                    ByVal P3 As String,  _
                    ByVal P4 As String,  _
                    ByVal Product As String,  _
                    ByVal PSP As Single,  _
                    ByVal PU As String,  _
                    ByVal PU2 As String,  _
                    ByVal PY1 As String,  _
                    ByVal PY3 As String,  _
                    ByVal R1A As String,  _
                    ByVal R1B As String,  _
                    ByVal R2A As String,  _
                    ByVal R2B As String,  _
                    ByVal R3 As String,  _
                    ByVal R4 As String,  _
                    ByVal RU As String,  _
                    ByVal RU2 As String,  _
                    ByVal RY1 As String,  _
                    ByVal RY3 As String,  _
                    ByVal SizeThk As String,  _
                    ByVal Spec As String,  _
                    ByVal TypeGrade As String,  _
                    ByVal Volta As Short) As ListaMatRow
            Dim rowListaMatRow As ListaMatRow = CType(Me.NewRow,ListaMatRow)
            rowListaMatRow.ItemArray = New Object() {AlfaCod, AlloyUNS, Caract1, Caract2, Caract3, Caract4, CAT, ClassCondTemp, Classe, CMT, Composiz, ConducTer, CT, Description, ElasCod, Nothing, Ind, Mat, MatGroup, matId, NomeComm, Notes, Notes2, Obsoleto, Ordinamento, P1A, P1B, P2A, P2B, P3, P4, Product, PSP, PU, PU2, PY1, PY3, R1A, R1B, R2A, R2B, R3, R4, RU, RU2, RY1, RY3, SizeThk, Spec, TypeGrade, Volta}
            Me.Rows.Add(rowListaMatRow)
            Return rowListaMatRow
        End Function
        
        Public Function FindByID(ByVal ID As Integer) As ListaMatRow
            Return CType(Me.Rows.Find(New Object() {ID}),ListaMatRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As ListaMatDataTable = CType(MyBase.Clone,ListaMatDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New ListaMatDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnAlfaCod = Me.Columns("AlfaCod")
            Me.columnAlloyUNS = Me.Columns("AlloyUNS")
            Me.columnCaract1 = Me.Columns("Caract1")
            Me.columnCaract2 = Me.Columns("Caract2")
            Me.columnCaract3 = Me.Columns("Caract3")
            Me.columnCaract4 = Me.Columns("Caract4")
            Me.columnCAT = Me.Columns("CAT")
            Me.columnClassCondTemp = Me.Columns("ClassCondTemp")
            Me.columnClasse = Me.Columns("Classe")
            Me.columnCMT = Me.Columns("CMT")
            Me.columnComposiz = Me.Columns("Composiz")
            Me.columnConducTer = Me.Columns("ConducTer")
            Me.columnCT = Me.Columns("CT")
            Me.columnDescription = Me.Columns("Description")
            Me.columnElasCod = Me.Columns("ElasCod")
            Me.columnID = Me.Columns("ID")
            Me.columnInd = Me.Columns("Ind")
            Me.columnMat = Me.Columns("Mat")
            Me.columnMatGroup = Me.Columns("MatGroup")
            Me.columnmatId = Me.Columns("matId")
            Me.columnNomeComm = Me.Columns("NomeComm")
            Me.columnNotes = Me.Columns("Notes")
            Me.columnNotes2 = Me.Columns("Notes2")
            Me.columnObsoleto = Me.Columns("Obsoleto")
            Me.columnOrdinamento = Me.Columns("Ordinamento")
            Me.columnP1A = Me.Columns("P1A")
            Me.columnP1B = Me.Columns("P1B")
            Me.columnP2A = Me.Columns("P2A")
            Me.columnP2B = Me.Columns("P2B")
            Me.columnP3 = Me.Columns("P3")
            Me.columnP4 = Me.Columns("P4")
            Me.columnProduct = Me.Columns("Product")
            Me.columnPSP = Me.Columns("PSP")
            Me.columnPU = Me.Columns("PU")
            Me.columnPU2 = Me.Columns("PU2")
            Me.columnPY1 = Me.Columns("PY1")
            Me.columnPY3 = Me.Columns("PY3")
            Me.columnR1A = Me.Columns("R1A")
            Me.columnR1B = Me.Columns("R1B")
            Me.columnR2A = Me.Columns("R2A")
            Me.columnR2B = Me.Columns("R2B")
            Me.columnR3 = Me.Columns("R3")
            Me.columnR4 = Me.Columns("R4")
            Me.columnRU = Me.Columns("RU")
            Me.columnRU2 = Me.Columns("RU2")
            Me.columnRY1 = Me.Columns("RY1")
            Me.columnRY3 = Me.Columns("RY3")
            Me.columnSizeThk = Me.Columns("SizeThk")
            Me.columnSpec = Me.Columns("Spec")
            Me.columnTypeGrade = Me.Columns("TypeGrade")
            Me.columnVolta = Me.Columns("Volta")
        End Sub
        
        Private Sub InitClass()
            Me.columnAlfaCod = New DataColumn("AlfaCod", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAlfaCod)
            Me.columnAlloyUNS = New DataColumn("AlloyUNS", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAlloyUNS)
            Me.columnCaract1 = New DataColumn("Caract1", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCaract1)
            Me.columnCaract2 = New DataColumn("Caract2", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCaract2)
            Me.columnCaract3 = New DataColumn("Caract3", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCaract3)
            Me.columnCaract4 = New DataColumn("Caract4", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCaract4)
            Me.columnCAT = New DataColumn("CAT", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCAT)
            Me.columnClassCondTemp = New DataColumn("ClassCondTemp", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnClassCondTemp)
            Me.columnClasse = New DataColumn("Classe", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnClasse)
            Me.columnCMT = New DataColumn("CMT", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCMT)
            Me.columnComposiz = New DataColumn("Composiz", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnComposiz)
            Me.columnConducTer = New DataColumn("ConducTer", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnConducTer)
            Me.columnCT = New DataColumn("CT", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCT)
            Me.columnDescription = New DataColumn("Description", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDescription)
            Me.columnElasCod = New DataColumn("ElasCod", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnElasCod)
            Me.columnID = New DataColumn("ID", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnID)
            Me.columnInd = New DataColumn("Ind", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnInd)
            Me.columnMat = New DataColumn("Mat", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnMat)
            Me.columnMatGroup = New DataColumn("MatGroup", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnMatGroup)
            Me.columnmatId = New DataColumn("matId", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnmatId)
            Me.columnNomeComm = New DataColumn("NomeComm", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNomeComm)
            Me.columnNotes = New DataColumn("Notes", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNotes)
            Me.columnNotes2 = New DataColumn("Notes2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNotes2)
            Me.columnObsoleto = New DataColumn("Obsoleto", GetType(System.Boolean), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnObsoleto)
            Me.columnOrdinamento = New DataColumn("Ordinamento", GetType(System.Single), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnOrdinamento)
            Me.columnP1A = New DataColumn("P1A", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnP1A)
            Me.columnP1B = New DataColumn("P1B", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnP1B)
            Me.columnP2A = New DataColumn("P2A", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnP2A)
            Me.columnP2B = New DataColumn("P2B", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnP2B)
            Me.columnP3 = New DataColumn("P3", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnP3)
            Me.columnP4 = New DataColumn("P4", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnP4)
            Me.columnProduct = New DataColumn("Product", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnProduct)
            Me.columnPSP = New DataColumn("PSP", GetType(System.Single), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPSP)
            Me.columnPU = New DataColumn("PU", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPU)
            Me.columnPU2 = New DataColumn("PU2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPU2)
            Me.columnPY1 = New DataColumn("PY1", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPY1)
            Me.columnPY3 = New DataColumn("PY3", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPY3)
            Me.columnR1A = New DataColumn("R1A", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnR1A)
            Me.columnR1B = New DataColumn("R1B", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnR1B)
            Me.columnR2A = New DataColumn("R2A", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnR2A)
            Me.columnR2B = New DataColumn("R2B", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnR2B)
            Me.columnR3 = New DataColumn("R3", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnR3)
            Me.columnR4 = New DataColumn("R4", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnR4)
            Me.columnRU = New DataColumn("RU", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRU)
            Me.columnRU2 = New DataColumn("RU2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRU2)
            Me.columnRY1 = New DataColumn("RY1", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRY1)
            Me.columnRY3 = New DataColumn("RY3", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRY3)
            Me.columnSizeThk = New DataColumn("SizeThk", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSizeThk)
            Me.columnSpec = New DataColumn("Spec", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSpec)
            Me.columnTypeGrade = New DataColumn("TypeGrade", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTypeGrade)
            Me.columnVolta = New DataColumn("Volta", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVolta)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnID}, true))
            Me.columnID.AutoIncrement = true
            Me.columnID.AllowDBNull = false
            Me.columnID.Unique = true
        End Sub
        
        Public Function NewListaMatRow() As ListaMatRow
            Return CType(Me.NewRow,ListaMatRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New ListaMatRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(ListaMatRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.ListaMatRowChangedEvent) Is Nothing) Then
                RaiseEvent ListaMatRowChanged(Me, New ListaMatRowChangeEvent(CType(e.Row,ListaMatRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.ListaMatRowChangingEvent) Is Nothing) Then
                RaiseEvent ListaMatRowChanging(Me, New ListaMatRowChangeEvent(CType(e.Row,ListaMatRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.ListaMatRowDeletedEvent) Is Nothing) Then
                RaiseEvent ListaMatRowDeleted(Me, New ListaMatRowChangeEvent(CType(e.Row,ListaMatRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.ListaMatRowDeletingEvent) Is Nothing) Then
                RaiseEvent ListaMatRowDeleting(Me, New ListaMatRowChangeEvent(CType(e.Row,ListaMatRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveListaMatRow(ByVal row As ListaMatRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ListaMatRow
        Inherits DataRow
        
        Private tableListaMat As ListaMatDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableListaMat = CType(Me.Table,ListaMatDataTable)
        End Sub
        
        Public Property AlfaCod As Short
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.AlfaCodColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.AlfaCodColumn) = value
            End Set
        End Property
        
        Public Property AlloyUNS As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.AlloyUNSColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.AlloyUNSColumn) = value
            End Set
        End Property
        
        Public Property Caract1 As Integer
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.Caract1Column),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.Caract1Column) = value
            End Set
        End Property
        
        Public Property Caract2 As Integer
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.Caract2Column),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.Caract2Column) = value
            End Set
        End Property
        
        Public Property Caract3 As Integer
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.Caract3Column),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.Caract3Column) = value
            End Set
        End Property
        
        Public Property Caract4 As Integer
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.Caract4Column),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.Caract4Column) = value
            End Set
        End Property
        
        Public Property CAT As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.CATColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.CATColumn) = value
            End Set
        End Property
        
        Public Property ClassCondTemp As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.ClassCondTempColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.ClassCondTempColumn) = value
            End Set
        End Property
        
        Public Property Classe As Short
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.ClasseColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.ClasseColumn) = value
            End Set
        End Property
        
        Public Property CMT As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.CMTColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.CMTColumn) = value
            End Set
        End Property
        
        Public Property Composiz As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.ComposizColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.ComposizColumn) = value
            End Set
        End Property
        
        Public Property ConducTer As Short
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.ConducTerColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.ConducTerColumn) = value
            End Set
        End Property
        
        Public Property CT As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.CTColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.CTColumn) = value
            End Set
        End Property
        
        Public Property Description As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.DescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.DescriptionColumn) = value
            End Set
        End Property
        
        Public Property ElasCod As Short
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.ElasCodColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.ElasCodColumn) = value
            End Set
        End Property
        
        Public Property ID As Integer
            Get
                Return CType(Me(Me.tableListaMat.IDColumn),Integer)
            End Get
            Set
                Me(Me.tableListaMat.IDColumn) = value
            End Set
        End Property
        
        Public Property Ind As Short
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.IndColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.IndColumn) = value
            End Set
        End Property
        
        Public Property Mat As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.MatColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.MatColumn) = value
            End Set
        End Property
        
        Public Property MatGroup As Short
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.MatGroupColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.MatGroupColumn) = value
            End Set
        End Property
        
        Public Property matId As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.matIdColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.matIdColumn) = value
            End Set
        End Property
        
        Public Property NomeComm As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.NomeCommColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.NomeCommColumn) = value
            End Set
        End Property
        
        Public Property Notes As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.NotesColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.NotesColumn) = value
            End Set
        End Property
        
        Public Property Notes2 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.Notes2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.Notes2Column) = value
            End Set
        End Property
        
        Public Property Obsoleto As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.ObsoletoColumn),Boolean)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.ObsoletoColumn) = value
            End Set
        End Property
        
        Public Property Ordinamento As Single
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.OrdinamentoColumn),Single)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.OrdinamentoColumn) = value
            End Set
        End Property
        
        Public Property P1A As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.P1AColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.P1AColumn) = value
            End Set
        End Property
        
        Public Property P1B As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.P1BColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.P1BColumn) = value
            End Set
        End Property
        
        Public Property P2A As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.P2AColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.P2AColumn) = value
            End Set
        End Property
        
        Public Property P2B As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.P2BColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.P2BColumn) = value
            End Set
        End Property
        
        Public Property P3 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.P3Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.P3Column) = value
            End Set
        End Property
        
        Public Property P4 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.P4Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.P4Column) = value
            End Set
        End Property
        
        Public Property Product As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.ProductColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.ProductColumn) = value
            End Set
        End Property
        
        Public Property PSP As Single
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.PSPColumn),Single)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.PSPColumn) = value
            End Set
        End Property
        
        Public Property PU As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.PUColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.PUColumn) = value
            End Set
        End Property
        
        Public Property PU2 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.PU2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.PU2Column) = value
            End Set
        End Property
        
        Public Property PY1 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.PY1Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.PY1Column) = value
            End Set
        End Property
        
        Public Property PY3 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.PY3Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.PY3Column) = value
            End Set
        End Property
        
        Public Property R1A As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.R1AColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.R1AColumn) = value
            End Set
        End Property
        
        Public Property R1B As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.R1BColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.R1BColumn) = value
            End Set
        End Property
        
        Public Property R2A As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.R2AColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.R2AColumn) = value
            End Set
        End Property
        
        Public Property R2B As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.R2BColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.R2BColumn) = value
            End Set
        End Property
        
        Public Property R3 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.R3Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.R3Column) = value
            End Set
        End Property
        
        Public Property R4 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.R4Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.R4Column) = value
            End Set
        End Property
        
        Public Property RU As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.RUColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.RUColumn) = value
            End Set
        End Property
        
        Public Property RU2 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.RU2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.RU2Column) = value
            End Set
        End Property
        
        Public Property RY1 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.RY1Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.RY1Column) = value
            End Set
        End Property
        
        Public Property RY3 As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.RY3Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.RY3Column) = value
            End Set
        End Property
        
        Public Property SizeThk As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.SizeThkColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.SizeThkColumn) = value
            End Set
        End Property
        
        Public Property Spec As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.SpecColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.SpecColumn) = value
            End Set
        End Property
        
        Public Property TypeGrade As String
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.TypeGradeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.TypeGradeColumn) = value
            End Set
        End Property
        
        Public Property Volta As Short
            Get
                Try 
                    Return CType(Me(Me.tableListaMat.VoltaColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableListaMat.VoltaColumn) = value
            End Set
        End Property
        
        Public Function IsAlfaCodNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.AlfaCodColumn)
        End Function
        
        Public Sub SetAlfaCodNull()
            Me(Me.tableListaMat.AlfaCodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsAlloyUNSNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.AlloyUNSColumn)
        End Function
        
        Public Sub SetAlloyUNSNull()
            Me(Me.tableListaMat.AlloyUNSColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCaract1Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.Caract1Column)
        End Function
        
        Public Sub SetCaract1Null()
            Me(Me.tableListaMat.Caract1Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsCaract2Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.Caract2Column)
        End Function
        
        Public Sub SetCaract2Null()
            Me(Me.tableListaMat.Caract2Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsCaract3Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.Caract3Column)
        End Function
        
        Public Sub SetCaract3Null()
            Me(Me.tableListaMat.Caract3Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsCaract4Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.Caract4Column)
        End Function
        
        Public Sub SetCaract4Null()
            Me(Me.tableListaMat.Caract4Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsCATNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.CATColumn)
        End Function
        
        Public Sub SetCATNull()
            Me(Me.tableListaMat.CATColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsClassCondTempNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.ClassCondTempColumn)
        End Function
        
        Public Sub SetClassCondTempNull()
            Me(Me.tableListaMat.ClassCondTempColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsClasseNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.ClasseColumn)
        End Function
        
        Public Sub SetClasseNull()
            Me(Me.tableListaMat.ClasseColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCMTNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.CMTColumn)
        End Function
        
        Public Sub SetCMTNull()
            Me(Me.tableListaMat.CMTColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsComposizNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.ComposizColumn)
        End Function
        
        Public Sub SetComposizNull()
            Me(Me.tableListaMat.ComposizColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsConducTerNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.ConducTerColumn)
        End Function
        
        Public Sub SetConducTerNull()
            Me(Me.tableListaMat.ConducTerColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCTNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.CTColumn)
        End Function
        
        Public Sub SetCTNull()
            Me(Me.tableListaMat.CTColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDescriptionNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.DescriptionColumn)
        End Function
        
        Public Sub SetDescriptionNull()
            Me(Me.tableListaMat.DescriptionColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsElasCodNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.ElasCodColumn)
        End Function
        
        Public Sub SetElasCodNull()
            Me(Me.tableListaMat.ElasCodColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsIndNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.IndColumn)
        End Function
        
        Public Sub SetIndNull()
            Me(Me.tableListaMat.IndColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsMatNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.MatColumn)
        End Function
        
        Public Sub SetMatNull()
            Me(Me.tableListaMat.MatColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsMatGroupNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.MatGroupColumn)
        End Function
        
        Public Sub SetMatGroupNull()
            Me(Me.tableListaMat.MatGroupColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsmatIdNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.matIdColumn)
        End Function
        
        Public Sub SetmatIdNull()
            Me(Me.tableListaMat.matIdColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNomeCommNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.NomeCommColumn)
        End Function
        
        Public Sub SetNomeCommNull()
            Me(Me.tableListaMat.NomeCommColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNotesNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.NotesColumn)
        End Function
        
        Public Sub SetNotesNull()
            Me(Me.tableListaMat.NotesColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNotes2Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.Notes2Column)
        End Function
        
        Public Sub SetNotes2Null()
            Me(Me.tableListaMat.Notes2Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsObsoletoNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.ObsoletoColumn)
        End Function
        
        Public Sub SetObsoletoNull()
            Me(Me.tableListaMat.ObsoletoColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsOrdinamentoNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.OrdinamentoColumn)
        End Function
        
        Public Sub SetOrdinamentoNull()
            Me(Me.tableListaMat.OrdinamentoColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsP1ANull() As Boolean
            Return Me.IsNull(Me.tableListaMat.P1AColumn)
        End Function
        
        Public Sub SetP1ANull()
            Me(Me.tableListaMat.P1AColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsP1BNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.P1BColumn)
        End Function
        
        Public Sub SetP1BNull()
            Me(Me.tableListaMat.P1BColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsP2ANull() As Boolean
            Return Me.IsNull(Me.tableListaMat.P2AColumn)
        End Function
        
        Public Sub SetP2ANull()
            Me(Me.tableListaMat.P2AColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsP2BNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.P2BColumn)
        End Function
        
        Public Sub SetP2BNull()
            Me(Me.tableListaMat.P2BColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsP3Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.P3Column)
        End Function
        
        Public Sub SetP3Null()
            Me(Me.tableListaMat.P3Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsP4Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.P4Column)
        End Function
        
        Public Sub SetP4Null()
            Me(Me.tableListaMat.P4Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsProductNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.ProductColumn)
        End Function
        
        Public Sub SetProductNull()
            Me(Me.tableListaMat.ProductColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPSPNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.PSPColumn)
        End Function
        
        Public Sub SetPSPNull()
            Me(Me.tableListaMat.PSPColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPUNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.PUColumn)
        End Function
        
        Public Sub SetPUNull()
            Me(Me.tableListaMat.PUColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPU2Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.PU2Column)
        End Function
        
        Public Sub SetPU2Null()
            Me(Me.tableListaMat.PU2Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsPY1Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.PY1Column)
        End Function
        
        Public Sub SetPY1Null()
            Me(Me.tableListaMat.PY1Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsPY3Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.PY3Column)
        End Function
        
        Public Sub SetPY3Null()
            Me(Me.tableListaMat.PY3Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsR1ANull() As Boolean
            Return Me.IsNull(Me.tableListaMat.R1AColumn)
        End Function
        
        Public Sub SetR1ANull()
            Me(Me.tableListaMat.R1AColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsR1BNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.R1BColumn)
        End Function
        
        Public Sub SetR1BNull()
            Me(Me.tableListaMat.R1BColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsR2ANull() As Boolean
            Return Me.IsNull(Me.tableListaMat.R2AColumn)
        End Function
        
        Public Sub SetR2ANull()
            Me(Me.tableListaMat.R2AColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsR2BNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.R2BColumn)
        End Function
        
        Public Sub SetR2BNull()
            Me(Me.tableListaMat.R2BColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsR3Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.R3Column)
        End Function
        
        Public Sub SetR3Null()
            Me(Me.tableListaMat.R3Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsR4Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.R4Column)
        End Function
        
        Public Sub SetR4Null()
            Me(Me.tableListaMat.R4Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsRUNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.RUColumn)
        End Function
        
        Public Sub SetRUNull()
            Me(Me.tableListaMat.RUColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsRU2Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.RU2Column)
        End Function
        
        Public Sub SetRU2Null()
            Me(Me.tableListaMat.RU2Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsRY1Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.RY1Column)
        End Function
        
        Public Sub SetRY1Null()
            Me(Me.tableListaMat.RY1Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsRY3Null() As Boolean
            Return Me.IsNull(Me.tableListaMat.RY3Column)
        End Function
        
        Public Sub SetRY3Null()
            Me(Me.tableListaMat.RY3Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsSizeThkNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.SizeThkColumn)
        End Function
        
        Public Sub SetSizeThkNull()
            Me(Me.tableListaMat.SizeThkColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSpecNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.SpecColumn)
        End Function
        
        Public Sub SetSpecNull()
            Me(Me.tableListaMat.SpecColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTypeGradeNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.TypeGradeColumn)
        End Function
        
        Public Sub SetTypeGradeNull()
            Me(Me.tableListaMat.TypeGradeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsVoltaNull() As Boolean
            Return Me.IsNull(Me.tableListaMat.VoltaColumn)
        End Function
        
        Public Sub SetVoltaNull()
            Me(Me.tableListaMat.VoltaColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ListaMatRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As ListaMatRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As ListaMatRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As ListaMatRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
