'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsCommesse
    Inherits DataSet
    
    Private tableAutorizz As AutorizzDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Autorizz")) Is Nothing) Then
                Me.Tables.Add(New AutorizzDataTable(ds.Tables("Autorizz")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Autorizz As AutorizzDataTable
        Get
            Return Me.tableAutorizz
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsCommesse = CType(MyBase.Clone,dsCommesse)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Autorizz")) Is Nothing) Then
            Me.Tables.Add(New AutorizzDataTable(ds.Tables("Autorizz")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableAutorizz = CType(Me.Tables("Autorizz"),AutorizzDataTable)
        If (Not (Me.tableAutorizz) Is Nothing) Then
            Me.tableAutorizz.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsCommesse"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsCommesse.xsd"
        Me.Locale = New System.Globalization.CultureInfo("it-IT")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableAutorizz = New AutorizzDataTable
        Me.Tables.Add(Me.tableAutorizz)
    End Sub
    
    Private Function ShouldSerializeAutorizz() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub AutorizzRowChangeEventHandler(ByVal sender As Object, ByVal e As AutorizzRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AutorizzDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnID As DataColumn
        
        Private columnOperazione As DataColumn
        
        Private columnQualif1 As DataColumn
        
        Private columnQualif2 As DataColumn
        
        Private columnQualif3 As DataColumn
        
        Private columnQualif4 As DataColumn
        
        Private columnQualif5 As DataColumn
        
        Private columnQualif6 As DataColumn
        
        Private columnQualif7 As DataColumn
        
        Private columnQualif8 As DataColumn
        
        Private columnQualif9 As DataColumn
        
        Friend Sub New()
            MyBase.New("Autorizz")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property IDColumn As DataColumn
            Get
                Return Me.columnID
            End Get
        End Property
        
        Friend ReadOnly Property OperazioneColumn As DataColumn
            Get
                Return Me.columnOperazione
            End Get
        End Property
        
        Friend ReadOnly Property Qualif1Column As DataColumn
            Get
                Return Me.columnQualif1
            End Get
        End Property
        
        Friend ReadOnly Property Qualif2Column As DataColumn
            Get
                Return Me.columnQualif2
            End Get
        End Property
        
        Friend ReadOnly Property Qualif3Column As DataColumn
            Get
                Return Me.columnQualif3
            End Get
        End Property
        
        Friend ReadOnly Property Qualif4Column As DataColumn
            Get
                Return Me.columnQualif4
            End Get
        End Property
        
        Friend ReadOnly Property Qualif5Column As DataColumn
            Get
                Return Me.columnQualif5
            End Get
        End Property
        
        Friend ReadOnly Property Qualif6Column As DataColumn
            Get
                Return Me.columnQualif6
            End Get
        End Property
        
        Friend ReadOnly Property Qualif7Column As DataColumn
            Get
                Return Me.columnQualif7
            End Get
        End Property
        
        Friend ReadOnly Property Qualif8Column As DataColumn
            Get
                Return Me.columnQualif8
            End Get
        End Property
        
        Friend ReadOnly Property Qualif9Column As DataColumn
            Get
                Return Me.columnQualif9
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As AutorizzRow
            Get
                Return CType(Me.Rows(index),AutorizzRow)
            End Get
        End Property
        
        Public Event AutorizzRowChanged As AutorizzRowChangeEventHandler
        
        Public Event AutorizzRowChanging As AutorizzRowChangeEventHandler
        
        Public Event AutorizzRowDeleted As AutorizzRowChangeEventHandler
        
        Public Event AutorizzRowDeleting As AutorizzRowChangeEventHandler
        
        Public Overloads Sub AddAutorizzRow(ByVal row As AutorizzRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddAutorizzRow(ByVal Operazione As String, ByVal Qualif1 As String, ByVal Qualif2 As String, ByVal Qualif3 As String, ByVal Qualif4 As String, ByVal Qualif5 As String, ByVal Qualif6 As String, ByVal Qualif7 As String, ByVal Qualif8 As String, ByVal Qualif9 As String) As AutorizzRow
            Dim rowAutorizzRow As AutorizzRow = CType(Me.NewRow,AutorizzRow)
            rowAutorizzRow.ItemArray = New Object() {Nothing, Operazione, Qualif1, Qualif2, Qualif3, Qualif4, Qualif5, Qualif6, Qualif7, Qualif8, Qualif9}
            Me.Rows.Add(rowAutorizzRow)
            Return rowAutorizzRow
        End Function
        
        Public Function FindByID(ByVal ID As Integer) As AutorizzRow
            Return CType(Me.Rows.Find(New Object() {ID}),AutorizzRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As AutorizzDataTable = CType(MyBase.Clone,AutorizzDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New AutorizzDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnID = Me.Columns("ID")
            Me.columnOperazione = Me.Columns("Operazione")
            Me.columnQualif1 = Me.Columns("Qualif1")
            Me.columnQualif2 = Me.Columns("Qualif2")
            Me.columnQualif3 = Me.Columns("Qualif3")
            Me.columnQualif4 = Me.Columns("Qualif4")
            Me.columnQualif5 = Me.Columns("Qualif5")
            Me.columnQualif6 = Me.Columns("Qualif6")
            Me.columnQualif7 = Me.Columns("Qualif7")
            Me.columnQualif8 = Me.Columns("Qualif8")
            Me.columnQualif9 = Me.Columns("Qualif9")
        End Sub
        
        Private Sub InitClass()
            Me.columnID = New DataColumn("ID", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnID)
            Me.columnOperazione = New DataColumn("Operazione", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnOperazione)
            Me.columnQualif1 = New DataColumn("Qualif1", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif1)
            Me.columnQualif2 = New DataColumn("Qualif2", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif2)
            Me.columnQualif3 = New DataColumn("Qualif3", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif3)
            Me.columnQualif4 = New DataColumn("Qualif4", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif4)
            Me.columnQualif5 = New DataColumn("Qualif5", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif5)
            Me.columnQualif6 = New DataColumn("Qualif6", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif6)
            Me.columnQualif7 = New DataColumn("Qualif7", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif7)
            Me.columnQualif8 = New DataColumn("Qualif8", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif8)
            Me.columnQualif9 = New DataColumn("Qualif9", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQualif9)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnID}, true))
            Me.columnID.AutoIncrement = true
            Me.columnID.AllowDBNull = false
            Me.columnID.Unique = true
        End Sub
        
        Public Function NewAutorizzRow() As AutorizzRow
            Return CType(Me.NewRow,AutorizzRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New AutorizzRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(AutorizzRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.AutorizzRowChangedEvent) Is Nothing) Then
                RaiseEvent AutorizzRowChanged(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.AutorizzRowChangingEvent) Is Nothing) Then
                RaiseEvent AutorizzRowChanging(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.AutorizzRowDeletedEvent) Is Nothing) Then
                RaiseEvent AutorizzRowDeleted(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.AutorizzRowDeletingEvent) Is Nothing) Then
                RaiseEvent AutorizzRowDeleting(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveAutorizzRow(ByVal row As AutorizzRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AutorizzRow
        Inherits DataRow
        
        Private tableAutorizz As AutorizzDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableAutorizz = CType(Me.Table,AutorizzDataTable)
        End Sub
        
        Public Property ID As Integer
            Get
                Return CType(Me(Me.tableAutorizz.IDColumn),Integer)
            End Get
            Set
                Me(Me.tableAutorizz.IDColumn) = value
            End Set
        End Property
        
        Public Property Operazione As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.OperazioneColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.OperazioneColumn) = value
            End Set
        End Property
        
        Public Property Qualif1 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif1Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif1Column) = value
            End Set
        End Property
        
        Public Property Qualif2 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif2Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif2Column) = value
            End Set
        End Property
        
        Public Property Qualif3 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif3Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif3Column) = value
            End Set
        End Property
        
        Public Property Qualif4 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif4Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif4Column) = value
            End Set
        End Property
        
        Public Property Qualif5 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif5Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif5Column) = value
            End Set
        End Property
        
        Public Property Qualif6 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif6Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif6Column) = value
            End Set
        End Property
        
        Public Property Qualif7 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif7Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif7Column) = value
            End Set
        End Property
        
        Public Property Qualif8 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif8Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif8Column) = value
            End Set
        End Property
        
        Public Property Qualif9 As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif9Column),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Impossibile ottenere un valore perché è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif9Column) = value
            End Set
        End Property
        
        Public Function IsOperazioneNull() As Boolean
            Return Me.IsNull(Me.tableAutorizz.OperazioneColumn)
        End Function
        
        Public Sub SetOperazioneNull()
            Me(Me.tableAutorizz.OperazioneColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif1Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif1Column)
        End Function
        
        Public Sub SetQualif1Null()
            Me(Me.tableAutorizz.Qualif1Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif2Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif2Column)
        End Function
        
        Public Sub SetQualif2Null()
            Me(Me.tableAutorizz.Qualif2Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif3Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif3Column)
        End Function
        
        Public Sub SetQualif3Null()
            Me(Me.tableAutorizz.Qualif3Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif4Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif4Column)
        End Function
        
        Public Sub SetQualif4Null()
            Me(Me.tableAutorizz.Qualif4Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif5Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif5Column)
        End Function
        
        Public Sub SetQualif5Null()
            Me(Me.tableAutorizz.Qualif5Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif6Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif6Column)
        End Function
        
        Public Sub SetQualif6Null()
            Me(Me.tableAutorizz.Qualif6Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif7Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif7Column)
        End Function
        
        Public Sub SetQualif7Null()
            Me(Me.tableAutorizz.Qualif7Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif8Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif8Column)
        End Function
        
        Public Sub SetQualif8Null()
            Me(Me.tableAutorizz.Qualif8Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsQualif9Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif9Column)
        End Function
        
        Public Sub SetQualif9Null()
            Me(Me.tableAutorizz.Qualif9Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class AutorizzRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As AutorizzRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As AutorizzRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As AutorizzRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
