ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                  SECTION VIII-DIVISION 1    1995 Edition                   บ
บpag.1                  PART UG GENERAL REQUIREMENTS                         บ
ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
บ          UG-39   REINFORCEMENT REQUIRED FOR OPENINGS IN FLAT HEADS         บ
ฬอออัออออออออออออออออออออออออออออออออออออออออออออออออออออัออออออัออออออออออออน
บvarณ                     descrizione                    ณdimen.ณ   valore   บ
ฬอออุออออออออออออออออออออออออออออออออออออออออออออออออออออุออออออุออออออออออออน
บT  ณ{\rtf\fs20{Nominal adopted cover thickness}}        ณ [mm] ณ            บ
บ{\rtf\fs20{C{\sub 0}}} ณ{\rtf\fs20{Cover corrosion}}    ณ [mm] ณ            บ
บ{\rtf\fs20{C{\sub g}}} ณ{\rtf\fs20{Cover pass partition grooves}} ณ [mm] ณ            บ
บt  ณ{\rtf\fs20{T - max(C{\sub 0},C{\sub g})}}           ณ [mm] ณ            บ
บ{\rtf\fs20{d{\sub i}}} ณInside diameter of nozzle                           ณ [mm] ณ            บ
บ{\rtf\fs20{d{\sub e}}} ณOutside diameter of nozzle                          ณ [mm] ณ            บ
บ{\rtf\fs20{T{\sub n}}} ณNominal nozzle thickness                            ณ [mm] ณ            บ
บ{\rtf\fs20{C{\sub n}}} ณNozzle corrosion                                    ณ [mm] ณ            บ
บ{\rtf\fs20{t{\sub n}}} ณ{\rtf\fs20{T{\sub n} - C{\sub n}}}                  ณ [mm] ณ            บ
บd  ณ{\rtf\fs20{d{\sub i} + 2.C{\sub n}}}                                    ณ [mm] ณ            บ
บ{\rtf\fs20{S{\sub na}}}ณAllowable design stress for nozzle at room          ณ [psi]ณ            บ
บ{\rtf\fs20{S{\sub no}}}ณAllowable design stress for nozzle at temp.         ณ [psi]ณ            บ
ศอออฯออออออออออออออออออออออออออออออออออออออออออออออออออออฯออออออฯออออออออออออผ
ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                 F2=run  F3=pagina avanti  F4=pagina indietro  F5=pagina n๘_บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

