ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                  SECTION VIII-DIVISION 1    1995 Edition                   บ
บpag.4                  PART UG GENERAL REQUIREMENTS                         บ
ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
บ          UG-39   REINFORCEMENT REQUIRED FOR OPENINGS IN FLAT HEADS         บ
ฬอออัออออออออออออออออออออออออออออออออออออออออออออออออออออัออออออัออออออออออออน
บvarณ                     descrizione                    ณdimen.ณ   valore   บ
ฬอออุออออออออออออออออออออออออออออออออออออออออออออออออออออุออออออุออออออออออออน
บja ณ{\rtf\fs16{(S{\sub ca}/S{\sub na}) if j{\sub a} <1 then j{\sub a} = 1}}ณ [--] ณ            บ
บjo ณ{\rtf\fs16{(S{\sub co}/S{\sub no}) if j{\sub o} <1 then j{\sub o} = 1}}ณ [--] ณ            บ
บA1oณ{\rtf\fs16{L.(t - t{\sub ro})}}                     ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
บA2oณ{\rtf\fs16{[H.(t{\sub n} - t{\sub rn})]/j{\sub o}}} ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
บA1aณ{\rtf\fs16{L.(t - t{\sub ra})}}                     ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
บA2aณ{\rtf\fs16{(H.t{\sub n}/j{\sub a})}}                ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
บARoณ{\rtf\fs16{A{\sub o} - (A{\sub 1o}+A{\sub 2o}).2    < 0}}ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
บARaณ{\rtf\fs16{A{\sub a} - (A{\sub 1a}+A{\sub 2a}).2    < 0}}ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
ศอออฯออออออออออออออออออออออออออออออออออออออออออออออออออออฯออออออฯออออออออออออผ




ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                 F2=run  F3=pagina avanti  F4=pagina indietro  F5=pagina n๘_บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

