'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Wald.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ARCK10.DAT.
        '''</summary>
        Friend ReadOnly Property Arck10() As String
            Get
                Return ResourceManager.GetString("Arck10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ARCK02.DAT.
        '''</summary>
        Friend ReadOnly Property Bubbledew() As String
            Get
                Return ResourceManager.GetString("Bubbledew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ARCK09.DAT.
        '''</summary>
        Friend ReadOnly Property Componenti() As String
            Get
                Return ResourceManager.GetString("Componenti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ARCK04.DAT.
        '''</summary>
        Friend ReadOnly Property Flash() As String
            Get
                Return ResourceManager.GetString("Flash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ARCK03.DAT.
        '''</summary>
        Friend ReadOnly Property Flashfraz() As String
            Get
                Return ResourceManager.GetString("Flashfraz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \BIN\AiutoWald.chm.
        '''</summary>
        Friend ReadOnly Property Helpfile() As String
            Get
                Return ResourceManager.GetString("Helpfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qualche dato di input potrebbe essere errato..
        '''</summary>
        Friend ReadOnly Property str1000() As String
            Get
                Return ResourceManager.GetString("str1000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il problema proposto potrebbe non essere risolubile..
        '''</summary>
        Friend ReadOnly Property str1010() As String
            Get
                Return ResourceManager.GetString("str1010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Funzione non implementata..
        '''</summary>
        Friend ReadOnly Property str1020() As String
            Get
                Return ResourceManager.GetString("str1020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non essendo presente acqua, si intende che|si vuole assegnare la frazione di idrocarburi liquidi..
        '''</summary>
        Friend ReadOnly Property str1030() As String
            Get
                Return ResourceManager.GetString("str1030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è possibile recuperare l&apos;output delle elaborazioni..
        '''</summary>
        Friend ReadOnly Property str1040() As String
            Get
                Return ResourceManager.GetString("str1040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;output delle elaborazioni è vuoto..
        '''</summary>
        Friend ReadOnly Property str1050() As String
            Get
                Return ResourceManager.GetString("str1050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ARCK01.DAT.
        '''</summary>
        Friend ReadOnly Property Trasformazioni() As String
            Get
                Return ResourceManager.GetString("Trasformazioni", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
