	SUBROUTINE KELVIN(X,LIMAG,INTDER,BERBEI,STDERR,NOMEFILE)
!DEC$ ATTRIBUTES DLLEXPORT::KELVIN
!DEC$ ATTRIBUTES STDCALL
C                             Declare variables
      TYPE BUFFER
	   CHARACTER*50 St
	END TYPE
	REAL*4 X,BERBEI
	INTEGER*2 STDERR,LIMAG,INTDER
	TYPE(BUFFER)::NOMEFILE
C--------------------------------------------------
      REAL*4       VALUE,BEI0,BER0,BEIP0,BERP0
      EXTERNAL     BEI0,BER0,BEIP0,BERP0,UMACH
!	LOGICAL QUESTION
C                                 Compute stdcall
	IF(LEN_TRIM(NOMEFILE%St).GT.0.AND.STDERR.GT.0) THEN
      CALL UMACH (-3, STDERR)
!	INQUIRE(FILE=NOMEFILE%St,EXIST=QUESTION)
!	IF(QUESTION) THEN
!	OPEN(UNIT=STDERR,FILE=NOMEFILE%St,STATUS='OLD')
!	CLOSE(STDERR,STATUS='DELETE')
!	ENDIF
      OPEN(UNIT=STDERR,FILE=NOMEFILE%St,MODE='WRITE',STATUS='UNKNOWN',
     $ ACCESS='APPEND')
      ENDIF
      SELECT CASE(LIMAG)
	CASE(1) !BER
	SELECT CASE(INTDER)
	CASE(0)
	VALUE=BER0(X)
	CASE(1)
	VALUE=BERP0(X)
	END SELECT
	CASE(2) !BEI
	SELECT CASE(INTDER)
	CASE(0)
	VALUE=BEI0(X)
	CASE(1)
	VALUE=BEIP0(X)
	END SELECT
	END SELECT
	IF(LEN_TRIM(NOMEFILE%St).GT.0)CLOSE(STDERR)
	BERBEI=VALUE
	RETURN
      END

