ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                  SECTION VIII-DIVISION 1    1995 Edition                   บ
บpag.3                  PART UG GENERAL REQUIREMENTS                         บ
ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
บ          UG-39   REINFORCEMENT REQUIRED FOR OPENINGS IN FLAT HEADS         บ
ฬอออัออออออออออออออออออออออออออออออออออออออออออออออออออออัออออออัออออออออออออน
บvarณ                     descrizione                    ณdimen.ณ   valore   บ
ฬอออุออออออออออออออออออออออออออออออออออออออออออออออออออออุออออออุออออออออออออน
บAa ณ{\rtf\fs20{0.5d.t{\sub ra}}}                       ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
บAo ณ{\rtf\fs20{0.5d.t{\sub ro}}}                       ณ{\rtf\fs16{[mm{\super 2}]}}ณ            บ
บtrnณ{\rtf\fs20{[P.d/2]/[S{\sub no} - 0.6P]}}           ณ [mm] ณ            บ
บh  ณ{\rtf\fs20{min[(2.5t);(2.5t{\sub n})]}}           ณ [mm] ณ            บ
บl  ณ{\rtf\fs20{max[d;(d/2+t{\sub n}+t)]}}               ณ [mm] ณ            บ
บH  ณh adopted (limits reinforcement on nozzle)          ณ [mm] ณ            บ
บL  ณl adopted (limits reinforcement on cover)           ณ [mm] ณ            บ
ศอออฯออออออออออออออออออออออออออออออออออออออออออออออออออออฯออออออฯออออออออออออผ

     (*) from nozzle axis
     (+) leave zero for automatic calculation


ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ                 F2=run  F3=pagina avanti  F4=pagina indietro  F5=pagina n๘_บ
ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ

