1      º\pard\plain \s18\qj\widctlpar\tx2835 \f2\fs18\lang1040 
S      º_\tab \                        \
s      º\par \tab ==========================
T      º_\par  \  \ * \                                        \ rev.\ \ (Date: \         \) *
V      º_\par                 \                                              \
1      º\par                 ==============================================
1      º\par          UG-39   REINFORCEMENT REQUIRED FOR OPENINGS IN FLAT HEADS
1      º\par          =========================================================
1      º\par 
N      º_\par COVER  IDENTIFICATION : &
O      º_\par COVER  MATERIAL       : &
P      º_\par NOZZLE MARK           : &
Q      º_\par NOZZLE MATERIAL       : &
1      º\par 
1      º\par 
1      º\par                              CALCULATION OF MAWP
1      º\par                              ===================
1      º\par 
A002   º_\par    Tem   = #########.## [°C]     #######.#### [°F]       Design temperature
1      º\par 
1      º\par Condition               MAWP         [MPa]    MAWP         [psi]    Controlling element
1      º\par ------------            ------------------    ------------------    -------------------
U003   º_\par Cold and new            #######.####          ##########.#          \               \
U004   º_\par Hot  and new            #######.####          ##########.#          \               \
U005   º_\par Cold and corroded       #######.####          ##########.#          \               \
U006   º_\par Hot  and corroded       #######.####          ##########.#          \               \
1      º\par 
1      º\par 
0      º

