	USE DFLIB
	INTERFACE
	INTEGER*4 FUNCTION HANDLER(SIGID,EXCEPT)
!DEC$ ATTRIBUTES C::HANDLER
      INTEGER*4 IRET
	INTEGER*2 SIGID,EXCEPT
	END FUNCTION
	END INTERFACE 
C----------------------------------------------------------------------
C     - PROGRAM SELVA - 1         REVISION FEB,1988
C----------------------------------------------------------------------
!DEC$ ATTRIBUTES DLLIMPORT::/SYSTEM/,SELVA,PRNUOVER
      TYPE SCHEDE
	   CHARACTER*80 SK(100)
	END TYPE
	TYPE BUFFER
	  CHARACTER*40 STAMPA
      END TYPE
	COMMON/SYSTEM/IN,IO,KDOS,MDOS,LDOS,NDOS,NUOVER
      CHARACTER*40 FILIN,FILOUT
      TYPE(SCHEDE)::STREAM
	TYPE(BUFFER)::STAMPA
	IN=1
c      IO=3
      KDOS=IN
      MDOS=8
      LDOS=9
      NDOS=10
	FILIN='C:\BASE\ESEGUI\TEMP\SELVAINP.DAT'
	FILOUT='C:\BASE\ESEGUI\TEMP\SELVAOUT.DAT'
c      NUMAR=NARGS()
c      IF(NUMAR.GE.2) THEN
c      CALL GETARG(1,FILIN,ISTAT)
c      CALL GETARG(2,FILOUT,ISTAT)
      OPEN(IN,FILE=FILIN,STATUS='OLD',ERR=100,IOSTAT=IO1)
cccc      OPEN(IO,FILE=FILOUT,ERR=100,IOSTAT=IO2)
c      ELSE
c      OPEN(IN,FILE=' ',STATUS='OLD')
c      OPEN(IO,FILE=' ')
c      ENDIF
	IRET=SIGNALQQ(SIG$FPE,HANDLER)

	DO 1 I=1,100
	READ(IN,1000,END=2)STREAM%SK(I)
	IF(STREAM%SK(I)(1:4).EQ.'FINE')GOTO2
1	CONTINUE
2     CLOSE(IN)
	STAMPA%STAMPA=FILOUT
      CALL SELVA(STREAM,STAMPA)
      CALL PRNUOVER
c      CLOSE(IO)
100   STOP
1000	FORMAT(A80)
      END
	INTEGER*4 FUNCTION HANDLER(SIGID,EXCEPT)
!DEC$ ATTRIBUTES C::HANDLER
	INTEGER*2 SIGID,EXCEPT
	WRITE(*,*)'ERRORE'
	PAUSE
	END FUNCTION
