;Normative di calcolo della forza dovuta al vento
;Nell'introdurre nuove norme o variazioni i simboli p F ed A devono restare 
[not applicable] 
[ASCE 7 1995 Ed.]
p=.00256*(I*V)^2*4.882*9.81,{\rtf1\ansi N/m{\super 2}},formula
F=Cf*Gh*p*A,N,formula
I=Importance Factor,--,1.1
V=Wind velocity,mph,75
Cf=Shape factor,--,.8
Gh=Factor,--,1.2
A=Area,{\rtf1\ansi m{\super 2}},0
Formula={\rtf1\ansi p=.00256{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}(I{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}V){\super 2}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}4.882{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}9.81; F=C{\sub f}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}G{\sub h}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}p{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}A}
[BS CP3]
p=K*(S1*S2*S3*V)^2,{\rtf1\ansi N/m{\super 2}},formula
F=Cf*p*A,N,formula
K=1/2 air density,{\rtf1\ansi kg/m{\super 3}},.613
V=Wind velocity,m/s,40
S1=Factor,--,1
S2=Factor,--,1
S3=Factor,--,1
Cf=Shape factor,--,.8
A=Area,{\rtf1\ansi m{\super 2}},0
Formula={\rtf1\ansi p=K{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}(S{\sub 1}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}S{\sub 2}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}S{\sub 3}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}V){\super 2}; F=C{\sub f}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}p{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}A}