'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BreLock.ProjectResources", GetType(ProjectResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \Bin\AiutoBre.chm.
        '''</summary>
        Friend Shared ReadOnly Property Helpfile() As String
            Get
                Return ResourceManager.GetString("Helpfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,20}\pard\plain \s18\qj\widctlpar\tx5245\tx6379\tx7088 \f2\fs18\lang1040 BREECH LOCK CLOSURE TYPE H-H HEAT EXCHANGER\par.
        '''</summary>
        Friend Shared ReadOnly Property stop001() As String
            Get
                Return ResourceManager.GetString("stop001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b Design Data}}\par {0,1}
        '''Shell Side Design Temperature\tab [\&apos;b0C]\tab T{{\sub 1}}\tab ={1,11:F}\par {0,1}
        '''Tube  Side Design Temperature\tab [\&apos;b0C]\tab T{{\sub 2}}\tab ={2,11:F}\par {0,1}
        '''Tube Sheet Design Temperature\tab [\&apos;b0C]\tab T\tab ={3,11:F}\par \par {0,1}
        '''Shell Side Design Pressure\tab [MPa]\tab p{{\sub 1}}\tab ={4,11:F}\par {0,1}
        '''Tube  Side Design Pressure\tab [MPa]\tab p{{\sub 2}}\tab ={5,11:F}\par \par .
        '''</summary>
        Friend Shared ReadOnly Property stop002() As String
            Get
                Return ResourceManager.GetString("stop002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,20}\pard \tx5245\tx6379\tx7088 BREECH LOCK CLOSURE TYPE H-L HEAT EXCHANGER\par.
        '''</summary>
        Friend Shared ReadOnly Property stop003() As String
            Get
                Return ResourceManager.GetString("stop003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Differential Design Pressure\tab [MPa]\tab p{{\sub d}}\tab ={1,11:F}\par {0,1}
        '''Differential Shell Side Design Pressure\tab [MPa]\tab p{{\sub s}}\tab ={2,11:F}\par {0,1}
        '''Differential Shell Side Test   Pressure\tab [MPa]\tab p{{\sub t}}\tab ={3,11:F}\par\par {0,1}
        '''{{\b Shell Side Gasket Data}}\par {0,1}
        '''Gasket Material: {4,24}\par {0,1}
        '''Gasket Outside Diameter\tab [mm]\tab G{{\sub o1}}\tab ={5,11:F}\par {0,1}
        '''Gasket Width\tab [mm]\tab N{{\sub 1}}\tab ={6,11:F}\par {0,1}
        '''Nubbin Width\tab [mm]\tab w [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop004() As String
            Get
                Return ResourceManager.GetString("stop004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b Tube Side Gasket Data}}\par {0,1}Gasket Material: {1,24}\par {0,1}
        '''Gasket Outside Diameter\tab [mm]\tab G{{\sub o2}}\tab ={2,11:F}\par {0,1}
        '''Gasket Width\tab [mm]\tab N{{\sub 2}}\tab ={3,11:F}\par {0,1}
        '''Nubbin Width\tab [mm]\tab w{{\sub 2}}\tab ={4,11:F}\par {0,1}
        '''Gasket Reaction Diameter\tab [mm]\tab G{{\sub 2}}\tab ={5,11:F}\par {0,1}
        '''Effective Gasket Seating\tab [mm]\tab b{{\sub 2}}\tab ={6,11:F}\par {0,1}
        '''Gasket Factor\tab \tab m{{\sub 2}}\tab ={7,11:F}\par {0,1}
        '''Gasket Seating Load\tab [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop005() As String
            Get
                Return ResourceManager.GetString("stop005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {7,1}.- SHELL BARREL}}\par {0,1}
        '''Shell Barrel Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 1}}\tab [MPa]\tab S{{\sub s}}\tab ={2,11:F}\par {0,1}
        '''Shell Barrel Int. diameter\tab [mm]\tab D{{\sub s}}\tab ={3,11:F}\par {0,1}
        '''Shell corrosion/clad\tab [mm]\tab c{{\sub s}}\tab ={4,11:F}\par {0,1}
        '''Min.Req.Thk.(base mat+cor/clad)\tab [mm]\tab t{{\sub smin}}\tab ={5,11:F}\par {0,1}
        '''Adopted Shell Barrel Thickness\tab [mm]\tab t{{\sub s}}\tab ={6,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop006() As String
            Get
                Return ResourceManager.GetString("stop006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {7,1}.- HEMISPHERICAL HEAD}}\par {0,1}
        '''Hemispherical Head Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 1}}\tab [MPa]\tab S{{\sub h}}\tab ={2,11:F}\par {0,1} Hemispherical Head Int.Radius\tab [mm]\tab R{{\sub h}}\tab ={3,11:F}\par {0,1}
        '''Head  corrosion/clad\tab [mm]\tab c{{\sub h}}\tab ={4,11:F}\par {0,1}
        '''Min.Req.Thk.(bas.mat+cor/clad)\tab [mm]\tab t{{\sub hmin}}\tab ={5,11:F}\par {0,1}
        '''Adopted Hemisph.Head Thickness\tab [mm]\tab t{{\sub h}}\tab ={6,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop007() As String
            Get
                Return ResourceManager.GetString("stop007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {1,1}.- TUBE SHEET}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop008() As String
            Get
                Return ResourceManager.GetString("stop008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to non più usata.
        '''</summary>
        Friend Shared ReadOnly Property stop009() As String
            Get
                Return ResourceManager.GetString("stop009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Tube Sheet Material : {1,24}\par {0,1}
        '''Outside Tube Diameter\tab [mm]\tab D{{\sub et}}\tab ={2,11:F}\par {0,1}
        '''Tube Layout Pitch\tab [mm]\tab P{{\sub trac}}\tab ={3,11:F}\par {0,1}
        '''Tube Pattern  1=triangular / 2=square\tab \tab \tab ={4,11:D}\par {0,1}
        '''Allowable Stress at Design Temp.T\tab [MPa]\tab S{{\sub p}}\tab ={5,11:F}\par {0,1}
        '''Allowable Stress at Room Temp.\tab [MPa]\tab S{{\sub op}}\tab ={6,11:F}\par {0,1}
        '''Tube side corrosion/clad\tab [mm]\tab c{{\sub tt}}\tab ={7,11:F}\par {0,1}
        '''Shell  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop010() As String
            Get
                Return ResourceManager.GetString("stop010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Tubes Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T\tab [MPa]\tab S{{\sub t}}\tab ={2,11:F}\par {0,1}
        '''Allowable Stress at Room Temp.\tab [MPa]\tab S{{\sub ot}}\tab ={3,11:F}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop011() As String
            Get
                Return ResourceManager.GetString("stop011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Min.Req.Thk.(bas.mat+cor/clad)\tab [mm]\tab t{{\sub pmin}}\tab ={1,11:F}\par {0,1}
        '''Adopted Tube Sheet Thickness\tab [mm]\tab t{{\sub p}}\tab ={2,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop012() As String
            Get
                Return ResourceManager.GetString("stop012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {15,1}.- INTERNAL SCREWS for TUBE SHEET SET-UP}}\par {0,1}
        '''Screws Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 2}}\tab [MPa]\tab S{{\sub b}}\tab ={2,11:F}\par {0,1}Allowable Stress at Room Temp.\tab [MPa]\tab S{{\sub a}}\tab ={3,11:F}\par {0,1}
        '''Yield  Strength  at Room Temp.\tab [MPa]\tab S{{\sub y}}\tab ={4,11:F}\par {0,1}
        '''Allowable Stress for Hydraulic Test\tab [MPa]\tab 0.67S{{\sub y}}\tab ={5,11:F}\par\par {0,1}
        '''Nominal Diameter\tab {{\b {6,8} }}\tab ([mm]\tab ={7,1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop013() As String
            Get
                Return ResourceManager.GetString("stop013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Min.Req.Bolt Area (operating)\tab [mm{{\super 2}}]\tab A{{\sub m1}}\tab ={1,11:F}\par {0,1}
        '''Min.Req.Bolt Area (gasket seating)\tab [mm{{\super 2}}]\tab A{{\sub m2}}\tab ={2,11:F}\par {0,1}
        '''Min.Req.Bolt Area (hydraulic test)\tab [mm{{\super 2}}]\tab A{{\sub mo}}\tab ={3,11:F}\par\par {0,1}
        '''Min.Req.Bolt Area\tab [mm{{\super 2}}]\tab A{{\sub m}}\tab ={4,11:F}\par {0,1}
        '''Actual  Bolt Area\tab [mm{{\super 2}}]\tab A{{\sub b}}\tab ={5,11:F}\par\par {0,1}
        '''Load after plastic deformation\tab [N] \tab W{{\su [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop014() As String
            Get
                Return ResourceManager.GetString("stop014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Yield  Strength  at Design Temp.T{{\sub 2}}\tab [MPa]\tab S{{\sub yt}}\tab ={1,11:F}\par {0,1}
        '''Yield  Strength  at Room Temp.\tab [MPa]\tab S{{\sub y}}\tab ={2,11:F}\par\par {0,1}
        '''Allowable Stress for Hydraulic Test\tab [MPa]\tab 0.9S{{\sub y}}\tab ={3,11:F}\par\par {0,1}
        '''Int.Diameter of Split Ring\tab [mm]\tab B{{\sub 0}}\tab ={4,11:F}\par {0,1}
        '''Ext.Diameter of Split Ring\tab [mm]\tab A{{\sub 0}}\tab ={5,11:F}\par\par {0,1}
        '''Int.Diameter of Internal Ring\tab [mm]\tab B{{\sub 1}}\tab ={6,11:F}\par  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop015() As String
            Get
                Return ResourceManager.GetString("stop015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to non più usato.
        '''</summary>
        Friend Shared ReadOnly Property stop016() As String
            Get
                Return ResourceManager.GetString("stop016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {1,1}.- EXTERNAL SCREWS &amp; PUSH BARS for THREADED LOCK RING}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop017() As String
            Get
                Return ResourceManager.GetString("stop017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Screws &amp; Push Bars Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 2}}\tab [MPa]\tab S{{\sub b}}\tab ={2,11:F}\par{0,1}
        '''Allowable Stress at Room Temp.\tab [MPa]\tab S{{\sub a}}\tab ={3,11:F}\par{0,1}
        '''Ins.Diameter of Ext.Compression Ring\tab [mm]\tab G{{\sub 3}}\tab ={4,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop018() As String
            Get
                Return ResourceManager.GetString("stop018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {11,1}.1 Amount of Bolting Area Required for Int.Row of Screws &amp; Push Bars}}\par {0,1}
        '''Nominal Diameter\tab {{\b {1,8} }}\tab ([mm]\tab ={2,11:F})\par {0,1}
        '''Bolt Circle Diameter\tab [mm]\tab C{{\sub 2}}\tab ={3,11:F}\par {0,1}
        '''Cross Area of a Screw\tab [mm{{\super 2}}]\tab A{{\sub b2}}\tab ={4,11:F}\par {0,1}
        '''Diameter of Push Bars\tab [mm]\tab D{{\sub p2}}\tab ={5,11:F}\par {0,1}
        '''Number of Screws\tab \tab \tab n{{\sub b2}}\tab ={6,11:F}\par\par {0,1}
        '''Design Bolt Load (operating)\tab [N] \tab [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop019() As String
            Get
                Return ResourceManager.GetString("stop019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1}.2 Amount of Bolting Area Required for Ext.Row of Screws &amp; Push Bars}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop020() As String
            Get
                Return ResourceManager.GetString("stop020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1}.0 Stub ACME ANSI B1.8 15/16&quot; Thread Parameters}}\par.
        '''</summary>
        Friend Shared ReadOnly Property stop021() As String
            Get
                Return ResourceManager.GetString("stop021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Nominal Diameter\tab {{\b {1,8} }}\tab ([mm]\tab ={2,11:F})\par {0,1}
        '''Bolt Circle Diameter\tab [mm]\tab C{{\sub 3}}\tab ={3,11:F}\par {0,1}
        '''Cross Area of a Screw\tab [mm{{\super 2}}]\tab A{{\sub b3}}\tab ={4,11:F}\par {0,1}
        '''Diameter of Push Bars\tab [mm]\tab D{{\sub p3}}\tab ={5,11:F}\par {0,1}
        '''Adopted Number of Screws\tab \tab \tab n{{\sub b3}}\tab ={6,11:F}\par\par {0,1}
        '''Design Bolt Load (operating)\tab [N] \tab W{{\sub ext}}\tab ={7,11:F}\par {0,1}
        '''Design Bolt Load (seating)\tab [N] \tab W{{\s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop022() As String
            Get
                Return ResourceManager.GetString("stop022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {1,1}.- THREADED END CHANNEL &amp; LOCK RING}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop023() As String
            Get
                Return ResourceManager.GetString("stop023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to non più usato.
        '''</summary>
        Friend Shared ReadOnly Property stop024() As String
            Get
                Return ResourceManager.GetString("stop024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Threaded End Channel &amp; Lock Ring Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 2}}\tab [MPa]\tab S\tab ={2,11:F}\par {0,1}
        '''Allowable Stress at Room Temp.\tab [MPa]\tab S{{\sub o}}\tab ={3,11:F}\par {0,1}
        '''Yield  Strength  at Design Temp.T{{\sub 2}}\tab [MPa]\tab S{{\sub yt}}\tab ={4,11:F}\par {0,1}
        '''Yield  Strength  at Room Temp.\tab [MPa]\tab S{{\sub y}}\tab ={5,11:F}\par {0,1}
        '''Nominal Diameter of Screwed Lock Ring\tab [mm]\tab D{{\sub O}}\tab ={6,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop025() As String
            Get
                Return ResourceManager.GetString("stop025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1}.0 Stub ACME ANSI B1.8 Thread Parameters}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop026() As String
            Get
                Return ResourceManager.GetString("stop026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1}.0 Stub ACME ANSI B1.8 Thread Parameters}}\par.
        '''</summary>
        Friend Shared ReadOnly Property stop027() As String
            Get
                Return ResourceManager.GetString("stop027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Nominal pitch\tab [mm]\tab p\tab ={1,11:F}\par {0,1}
        '''Tooth height\tab [mm]\tab h\tab ={2,11:F}\par {0,1}
        '''Tooth root thickness\tab [mm]\tab a\tab ={3,11:F}\par {0,1}
        '''Outer nominal clearance\tab [mm]\tab G{{\sub o}}\tab ={4,11:F}\par {0,1}
        '''Inner nominal clearance\tab [mm]\tab G{{\sub i}}\tab ={5,11:F}\par {0,1}
        '''Thread dia on Lock Ring (@ min.tol.)\tab [mm]\tab D\tab ={6,11:F}\par {0,1}
        '''Throat dia on Channel (@max.tol.)\tab [mm]\tab D{{\sub 1}}\tab ={7,11:F}\par {0,1}
        '''Avg. dia of the threads\tab [m [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop028() As String
            Get
                Return ResourceManager.GetString("stop028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1:D}.1 Analysis of the Threaded Lock Ring}}\par.
        '''</summary>
        Friend Shared ReadOnly Property stop029() As String
            Get
                Return ResourceManager.GetString("stop029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Int.Diameter of Threaded Lock Ring\tab [mm]\tab B{{\sub 2}}\tab ={1,11:F}\par {0,1}
        '''Ext.Diameter of Channel Flat Cover\tab [mm]\tab B{{\sub 3}}\tab ={2,11:F}\par {0,1}
        '''Min.Req.Lock Ring Thk (operating)\tab [mm]\tab t{{\sub 3}}\tab ={3,11:F}\par {0,1}
        '''Min.Req.Lock Ring Thk (gasket seating)\tab [mm]\tab T{{\sub 3}}\tab ={4,11:F}\par\par {0,1}
        '''Min.Req.Lock Ring Thk\tab [mm]\tab t{{\sub 3min}}\tab ={5,11:F}\par {0,1}
        '''Adopted Lock Ring Thk\tab [mm]\tab t{{\sub 3}}\tab ={6,11:F}\par\par {0,1}
        '''Lock Ring [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop030() As String
            Get
                Return ResourceManager.GetString("stop030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1:D}.2 Analysis of the Thread}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop031() As String
            Get
                Return ResourceManager.GetString("stop031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Number of Engaged Threads\tab \tab z\tab ={1,11:F}\par\par {0,1}
        '''Thread Shearing   Stress (operating)\tab [MPa]\tab S{{\sub 1shear}}\tab ={2,11:F}\par {0,1}
        '''Allow. Shearing   Stress     \tab [MPa]\tab 0.6S\tab ={3,11:F}\par\par {0,1}
        '''Thread Bending    Stress     \tab [MPa]\tab S{{\sub 1bend}}\tab ={4,11:F}\par {0,1}
        '''Thread Equivalent Stress     \tab [MPa]\tab S{{\sub ige1}}\tab ={5,11:F}\par {0,1}
        '''Allow. Equivalent Stress     \tab [MPa]\tab S\tab ={6,11:F}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop032() As String
            Get
                Return ResourceManager.GetString("stop032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Thread Bearing    Stress     &quot;&quot;\tab [MPa]\tab S{{\sub 1bear}}\tab ={1,11:F}\par {0,1}
        '''Allow. Bearing    Stress     \tab [MPa]\tab S{{\sub yt}}\tab ={2,11:F}\par\par {0,1}
        '''Thread Shearing   Str. (gasket seating)\tab [MPa]\tab S{{\sub 2shear}}\tab ={3,11:F}\par {0,1}
        '''Allow. Shearing   Stress     \tab [MPa]\tab 0.6S{{\sub O}}\tab ={4,11:F}\par\par {0,1}
        '''Thread Bending    Stress     \tab [MPa]\tab S{{\sub 2bend}}\tab ={5,11:F}\par {0,1}
        '''Thread Equivalent Stress     \tab [MPa]\tab S{{\sub ige2}}\tab ={ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop033() As String
            Get
                Return ResourceManager.GetString("stop033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1:D}.3 Analysis of the Threaded End Channel}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop034() As String
            Get
                Return ResourceManager.GetString("stop034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Channel Threaded Length\tab [mm]\tab h{{\sub o}}\tab ={1,11:F}\par {0,1}
        '''Threaded End Channel Thickness\tab [mm]\tab t{{\sub o}}\tab ={2,11:F}\par {0,1}
        '''(*) Groove thk., section 4, see Explanatory notes\par {0,1}
        '''External Diameter of Channel\tab [mm]\tab D{{\sub oc}}\tab ={3,11:F}\par\par {0,1}
        '''Channel Long. Membrane (operating)\tab [MPa]\tab S{{\sub 1lm}}\tab ={4,11:F}\par {0,1}
        '''Max.Allowable Membrane\tab [MPa]\tab S\tab ={5,11:F}\par {0,1}
        '''Channel Long. Bending   \tab [MPa]\tab S{{\sub 1lb}}\ta [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop035() As String
            Get
                Return ResourceManager.GetString("stop035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {1,1:D}.- CHANNEL FLAT COVER}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop036() As String
            Get
                Return ResourceManager.GetString("stop036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Channel Flat Cover Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 2}}\tab [MPa]\tab S\tab ={2,11:F}\par {0,1}
        '''Yield  Strength  at Design Temp.T{{\sub 2}}\tab [MPa]\tab S{{\sub yt}}\tab ={3,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop037() As String
            Get
                Return ResourceManager.GetString("stop037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1:D}.1 Minimum Required Thickness}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop038() As String
            Get
                Return ResourceManager.GetString("stop038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Min.Req.Channel Flat Cover Thk\tab [mm]\tab t{{\sub fmin}}\tab ={1,11:F}\par {0,1}
        '''Adopted Channel Flat Cover Thk\tab [mm]\tab t{{\sub f}}\tab ={2,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop039() As String
            Get
                Return ResourceManager.GetString("stop039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1:D}.2 Analysis of the External Crown}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop040() As String
            Get
                Return ResourceManager.GetString("stop040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}External Crown Thickness\tab [mm]\tab t{{\sub fo}}\tab ={1,11:F}\par\par {0,1}
        '''Ext.Crown Shearing   Str.(operating)\tab [MPa]\tab S{{\sub 1shear}}\tab ={2,11:F}\par {0,1}
        '''Allowable Shearing   Str.     \tab [MPa]\tab 0.6S\tab ={3,11:F}\par\par {0,1}
        '''Ext.Crown Bending    Str.     \tab [MPa]\tab S{{\sub 1bend}}\tab ={4,11:F}\par {0,1}
        '''Ext.Crown Equivalent Str.     \tab [MPa]\tab S{{\sub ige1}}\tab ={5,11:F}\par\par {0,1}
        '''Allowable Equivalent Str.     \tab [MPa]\tab S\tab ={6,11:F}\par\par {0,1}
        '''Ext. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop041() As String
            Get
                Return ResourceManager.GetString("stop041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \par {0,1}{{\i {15,1}.4 Analysis of the internal box, conical shell}}\par {0,1}
        '''Int. Conical Shell Material : {1,24}\par {0,1}
        '''Modulus of Elasticity in Design\tab [MPa]\tab E{{\sub d}}\tab ={2,11:F}\par {0,1}
        '''Modulus of Elasticity in Test\tab [MPa]\tab E{{\sub t}}\tab ={3,11:F}\par {0,1}
        '''Thickness of Conical Shell\tab [mm]\tab t\tab ={4,11:F}\par {0,1}
        '''Max. Mean Diam. of Cone\tab [mm]\tab D{{\sub 1}}\tab ={5,11:F}\par {0,1}
        '''Min. Mean Diam. of Cone\tab [mm]\tab D{{\sub 2}}\tab ={6,11:F}\par {0,1}
        '''Int. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop042() As String
            Get
                Return ResourceManager.GetString("stop042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Area of Cone - minimum between area on the minimum diameter\par {0,1}
        '''of the conical shell and area on the section with openings :\par {0,1}
        '''    A{{\sub c}}        = {1,11:F}  mm{{\super 2}}\par\par {0,1}
        '''Maximum stress in :\par\par {0,1}
        '''Design     :  W{{\sub pl}}/A{{\sub c}} = {2,11:F}MPa\par {0,1}
        '''Bolting-up :  W{{\sub m2}}/A{{\sub c}} = {3,11:F}MPa\par {0,1}
        '''Test       :  W{{\sub mo}}/A{{\sub c}} = {4,11:F}MPa\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop043() As String
            Get
                Return ResourceManager.GetString("stop043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \par {0,1}{{\i {12,1}.1 Analysis of the Split Ring}}\par {0,1}
        '''Split Ring Thickness\tab [mm]\tab t{{\sub 1}}\tab ={1,11:F}\par {0,1}
        '''Split Ring Shear Str.(operating,W{{\sub pl}})\tab [MPa]\tab S{{\sub 1shear}}\tab ={2,11:F}\par {0,1}
        '''Allowable  Shear Str.    \tab [MPa]\tab 0.6S\tab ={3,11:F}\par\par {0,1}
        '''Split Ring Shear Str.(seating,W{{\sub m2}})\tab [MPa]\tab S{{\sub 2shear}}\tab ={4,11:F}\par {0,1}
        '''Allowable  Shear Str.    \tab [MPa]\tab 0.6S{{\sub o}}\tab ={5,11:F}\par\par {0,1}
        '''Split Ring Shear  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop044() As String
            Get
                Return ResourceManager.GetString("stop044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Split Ring Bearing Str.(hydr. test)\tab [MPa]\tab S{{\sub obear}}\tab ={1,11:F}\par {0,1}
        '''Allowable  bearing Str.    \tab [MPa]\tab S{{\sub y}}\tab ={2,11:F}\par\par{0,1}
        '''{{\i 5.2 Analysis of the Internal Ring}}\par {0,1}
        '''Min.Req.Int.Ring Thk (operating)\tab [mm]\tab t{{\sub 2}}\tab ={3,11:F}\par {0,1}
        '''Min.Req.Int.Ring Thk (seating)\tab [mm]\tab t{{\sub 2}}\tab ={4,11:F}\par {0,1}
        '''Min.Req.Int.Ring Thk (hydr. test)\tab [mm]\tab t{{\sub 2}}\tab ={5,11:F}\par {0,1}
        '''Min.Req.Int.Ring Thk\tab [mm]\tab  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop045() As String
            Get
                Return ResourceManager.GetString("stop045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {1,1:D}.- CHANNEL BARREL}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop046() As String
            Get
                Return ResourceManager.GetString("stop046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Channel Barrel Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 2}}\tab [MPa]\tab S{{\sub c}}\tab ={2,11:F}\par {0,1}
        '''Channel Barrel Int.Radius\tab [mm]\tab R{{\sub c}}\tab ={3,11:F}\par {0,1}
        '''Channel Barrel corrosion/clad\tab [mm]\tab c{{\sub bc}}\tab ={4,11:F}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop047() As String
            Get
                Return ResourceManager.GetString("stop047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}Min.Req.Thk (base mat+cor/clad+groove)\tab [mm]\tab t{{\sub cmin}}\tab ={1,11:F}\par {0,1}
        '''Adopted Channel Thk\tab [mm]\tab t{{\sub c}}\tab ={2,11:F}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop048() As String
            Get
                Return ResourceManager.GetString("stop048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {10,1}.3 Analysis of the Internal Box Flange}}\par {0,1}
        '''Internal Box Flange : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.   T{{\sub 2}}\tab [MPa]\tab S\tab ={2,11:F}\par {0,1}
        '''Allowable Stress at Room Temp.\tab [MPa]\tab S{{\sub o}}\tab ={3,11:F}\par {0,1}
        '''Yield Strength at Room Temp.\tab [MPa]\tab S{{\sub yo}}\tab ={4,11:F}\par\par {0,1}
        '''External Dia. of Flange\tab [mm]\tab D{{\sub of}}\tab ={5,11:F}\par {0,1}
        '''Internal Dia. of Flange\tab [mm]\tab D{{\sub if}}\tab ={6,11:F}\par\par {0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop049() As String
            Get
                Return ResourceManager.GetString("stop049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \par\par {0,1}NOTE The loads used for the calculation of the internal split ring,\par {0,1}
        '''the internal ring, internal screws and the internal box are given by:\par {0,1}
        '''         max(W{{\sub m1}},W{{\sub pl}}, W{{\sub m2}} + T{{\sub m2}}, W{{\sub mo}} + T{{\sub mo}}), with:\par\par {0,1}
        '''Additional load in oper. due to thermal exp.....[N]  W{{\sub pl}} = {1,13:F}\par {0,1}
        '''Additional load in seating......................[N]  T{{\sub m2}} ={2,13:F}\par {0,1}
        '''Additional load in hydr.test............... [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop050() As String
            Get
                Return ResourceManager.GetString("stop050", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b {9,1}.- INTERNAL RING &amp; SPLIT RING}}\par {0,1}
        '''Split Ring Material : {1,24}\par {0,1}
        '''Allowable Stress at Design Temp.T{{\sub 2}}\tab [MPa]\tab S\tab ={2,11:F}\par {0,1}
        '''Allowable stress at Room Temp.\tab [MPa]\tab S{{\sub o}}\tab ={3,11:F}\par {0,1}
        '''Yield  Strength  at Design Temp.T{{\sub 2}}\tab [MPa]\tab S{{\sub yt}}\tab ={4,11:F}\par {0,1}
        '''Yield  Strength  at Room Temp.\tab [MPa]\tab S{{\sub y}}\tab ={5,11:F}\par\par {0,1}
        '''Internal Ring Material : {6,24}\par {0,1}
        '''Allowable Stress at De [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop051() As String
            Get
                Return ResourceManager.GetString("stop051", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\i {1,1:D}.4 Notes}}\par .
        '''</summary>
        Friend Shared ReadOnly Property stop052() As String
            Get
                Return ResourceManager.GetString("stop052", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}The machining of the threads diameters is affected by a tolerance field\par {0,1}
        '''which lies entirely on the plus side for the holes and on the minus side\par .
        '''</summary>
        Friend Shared ReadOnly Property stop053() As String
            Get
                Return ResourceManager.GetString("stop053", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}for the shafts. The width of the tolerance field taken in account in the\par {0,1}
        '''present calculations is {{\b {1:0.0000} mm}}.\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop054() As String
            Get
                Return ResourceManager.GetString("stop054", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}The blow-up of the diameter of the channel threaded end because of the \par {0,1}
        '''pressure and mechanical loads produces a partial disengagement of the \par .
        '''</summary>
        Friend Shared ReadOnly Property stop055() As String
            Get
                Return ResourceManager.GetString("stop055", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}threaded coupling which is taken in account in the present calculations.\par {0,1}
        '''The calculated increase on the channel end radius has been {{\b {1:0.0000} mm}}\par in design conditions, and {{\b {2:##.###} mm}} in leak condition.\par \par  .
        '''</summary>
        Friend Shared ReadOnly Property stop056() As String
            Get
                Return ResourceManager.GetString("stop056", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}A transient metal temperature field, producing a further partial disengagement\par {0,1}
        '''of the threaded coupling has been considered. The temperature of the lock\par .
        '''</summary>
        Friend Shared ReadOnly Property stop057() As String
            Get
                Return ResourceManager.GetString("stop057", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}ring was {1:####.##}\&apos;b0C, the temperature of the channel end was {{\b {2:##.### \&apos;b0C}}, and\par {0,1}
        '''the resulting disengagement on the radius has been {{\b {3:##.### mm}}.\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop058() As String
            Get
                Return ResourceManager.GetString("stop058", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}The combination of all the effects described above gives, as a result, a \par {0,1}
        '''residual height of the engaged portion of the threads by {{\b {1:0.0000} mm}}\par in design conditions, and {{\b {2:0.0000} mm}} in leak condition.\par \par  .
        '''</summary>
        Friend Shared ReadOnly Property stop059() As String
            Get
                Return ResourceManager.GetString("stop059", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b Elastic diaphragm Data}}\par {0,1}
        '''Material : {1,24}\par {0,1}
        '''Elastic modulus @temp\tab [MPa]\tab E{{\sub d}}\tab ={2,11:F}\par {0,1}
        '''Minor thickness\tab [mm]\tab t\tab ={3,11:F}\par {0,1}
        '''Axial movement on int.row of screws\tab [mm]\tab y{{\sub 1}}\tab ={4,11:F}\par {0,1}
        '''Axial movement on ext.row of screws\tab [mm]\tab y{{\sub 2}}\tab ={5,11:F}\par {0,1}
        '''Raised width on int.row of screws\tab [mm]\tab l{{\sub 1}}\tab ={6,11:F}\par {0,1}
        '''Raised width on ext.row of screws\tab [mm]\tab l{{\s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property stop060() As String
            Get
                Return ResourceManager.GetString("stop060", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}{{\b Calculation options}}:\par {0,1}
        '''Differential pressure acting on both sides of the TS\tab \tab :{1,6}\par {0,1}
        '''Inner thermomechanical loads treated as primary loads\tab \tab :{2,6}\par {0,1}
        '''Pressurisation of the threaded channel in design condition\tab \tab :{3,6}\par\par .
        '''</summary>
        Friend Shared ReadOnly Property stop061() As String
            Get
                Return ResourceManager.GetString("stop061", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0,1}
        '''Maximum allowable longitudinal stress in compression (UG-23(a)/AD-340)\par\par {0,1}
        '''Chart: {3}\par {0,1}Factor A:   {4:0.00000}  (new)  {5:0.00000}  (corroded)\par {0,1}
        '''Allowable in Design \tab [MPa]\tab \tab = {1,11:F}\par {0,1}
        '''Allowable in Bolting-up &amp; Test\tab [MPa\tab \tab = {2,11:F}\par.
        '''</summary>
        Friend Shared ReadOnly Property stop062() As String
            Get
                Return ResourceManager.GetString("stop062", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Channel Long. Membrane (accident)\tab [MPa]\tab S{{\sub 3lm}}\tab ={1,11:F}\par {0,1}
        '''Max.Allowable Membrane\tab [MPa]\tab S{{\sub y}}\tab ={2,11:F}\par {0,1}
        '''Channel Long. Bending    \tab [MPa]\tab S{{\sub 3lb}}\tab ={3,11:F}\par {0,1}
        '''Channel Long. Combined     \tab [MPa]\tab S{{\sub 3l}}\tab ={4,11:F}\par {0,1}
        '''Max.Allowable Combined     \tab [MPa]\tab 1.35S{{\sub y}}\tab ={5,11:F}\par\par.
        '''</summary>
        Friend Shared ReadOnly Property stop063() As String
            Get
                Return ResourceManager.GetString("stop063", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Channel Long. Membrane (accident)\tab [MPa]\tab S{{\sub 3lm}}\tab ={1,11:F}\par {0,1}
        '''Max.Allowable Membrane\tab [MPa]\tab S\tab ={2,11:F}\par {0,1}
        '''Channel Long. Bending    \tab [MPa]\tab S{{\sub 3lb}}\tab ={3,11:F}\par {0,1}
        '''Channel Long. Combined     \tab [MPa]\tab S{{\sub 3l}}\tab ={4,11:F}\par {0,1}
        '''Max.Allowable Combined     \tab [MPa]\tab 1.5S\tab ={5,11:F}\par\par.
        '''</summary>
        Friend Shared ReadOnly Property stop064() As String
            Get
                Return ResourceManager.GetString("stop064", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mantello.
        '''</summary>
        Friend Shared ReadOnly Property str00001() As String
            Get
                Return ResourceManager.GetString("str00001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fondo lato mantello.
        '''</summary>
        Friend Shared ReadOnly Property str00002() As String
            Get
                Return ResourceManager.GetString("str00002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Piastra tubiera.
        '''</summary>
        Friend Shared ReadOnly Property str00003() As String
            Get
                Return ResourceManager.GetString("str00003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tubi.
        '''</summary>
        Friend Shared ReadOnly Property str00004() As String
            Get
                Return ResourceManager.GetString("str00004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cassa.
        '''</summary>
        Friend Shared ReadOnly Property str00005() As String
            Get
                Return ResourceManager.GetString("str00005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cassonetto.
        '''</summary>
        Friend Shared ReadOnly Property str00006() As String
            Get
                Return ResourceManager.GetString("str00006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flangia cassonetto.
        '''</summary>
        Friend Shared ReadOnly Property str00007() As String
            Get
                Return ResourceManager.GetString("str00007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anello a settori.
        '''</summary>
        Friend Shared ReadOnly Property str00008() As String
            Get
                Return ResourceManager.GetString("str00008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anello interno.
        '''</summary>
        Friend Shared ReadOnly Property str00009() As String
            Get
                Return ResourceManager.GetString("str00009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Viti interne.
        '''</summary>
        Friend Shared ReadOnly Property str00010() As String
            Get
                Return ResourceManager.GetString("str00010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Viti esterne.
        '''</summary>
        Friend Shared ReadOnly Property str00011() As String
            Get
                Return ResourceManager.GetString("str00011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anello di blocco.
        '''</summary>
        Friend Shared ReadOnly Property str00012() As String
            Get
                Return ResourceManager.GetString("str00012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tappo.
        '''</summary>
        Friend Shared ReadOnly Property str00013() As String
            Get
                Return ResourceManager.GetString("str00013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diaframma elastico.
        '''</summary>
        Friend Shared ReadOnly Property str00014() As String
            Get
                Return ResourceManager.GetString("str00014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inserto su flangia cassonetto.
        '''</summary>
        Friend Shared ReadOnly Property str00015() As String
            Get
                Return ResourceManager.GetString("str00015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completato il calcolo del mantello, del fondo, e della|guarnizione sotto la piastra tubiera..
        '''</summary>
        Friend Shared ReadOnly Property str00100() As String
            Get
                Return ResourceManager.GetString("str00100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completato il calcolo della piastra tubiera.|Scelta della pressione di spinta in prova|idraulica per il dimensionamento delle viti esterne..
        '''</summary>
        Friend Shared ReadOnly Property str00110() As String
            Get
                Return ResourceManager.GetString("str00110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completato il calcolo delle viti di spinta della PT.
        '''</summary>
        Friend Shared ReadOnly Property str00120() As String
            Get
                Return ResourceManager.GetString("str00120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completato il calcolo di split ring e inner ring.
        '''</summary>
        Friend Shared ReadOnly Property str00130() As String
            Get
                Return ResourceManager.GetString("str00130", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completata la verifica del cassonetto e della sua flangia superiore.
        '''</summary>
        Friend Shared ReadOnly Property str00140() As String
            Get
                Return ResourceManager.GetString("str00140", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calcolato lo spessore minimo della cassa e la larghezza attiva della guarnizione.
        '''</summary>
        Friend Shared ReadOnly Property str00150() As String
            Get
                Return ResourceManager.GetString("str00150", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Progetto completato delle due serie di viti di spinta.
        '''</summary>
        Friend Shared ReadOnly Property str00160() As String
            Get
                Return ResourceManager.GetString("str00160", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completata la verifica dell&apos;anello filettato.
        '''</summary>
        Friend Shared ReadOnly Property str00170() As String
            Get
                Return ResourceManager.GetString("str00170", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;ammissibile in temperatura del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00500() As String
            Get
                Return ResourceManager.GetString("str00500", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;ammissibile a temperatura ambiente del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00510() As String
            Get
                Return ResourceManager.GetString("str00510", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lo snervamento in temperatura del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00520() As String
            Get
                Return ResourceManager.GetString("str00520", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lo snervamento a temperatura ambiente del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00530() As String
            Get
                Return ResourceManager.GetString("str00530", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il modulo elastico in temperatura del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00540() As String
            Get
                Return ResourceManager.GetString("str00540", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il modulo elastico a temperatura ambiente del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00550() As String
            Get
                Return ResourceManager.GetString("str00550", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il coefficiente di dilatazione termica in temperatura del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00560() As String
            Get
                Return ResourceManager.GetString("str00560", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il coefficiente di dilatazione termica ambiente del materiale.
        '''</summary>
        Friend Shared ReadOnly Property str00570() As String
            Get
                Return ResourceManager.GetString("str00570", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to non è stato specificato correttamente.
        '''</summary>
        Friend Shared ReadOnly Property str00600() As String
            Get
                Return ResourceManager.GetString("str00600", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro esterno specificato per la guarnizione|sotto la piastra tubiera ha un valore poco plausibile.|Vuoi aggiornarlo secondo lo standard?.
        '''</summary>
        Friend Shared ReadOnly Property str00700() As String
            Get
                Return ResourceManager.GetString("str00700", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro esterno specificato per la guarnizione|sotto il diaframma elastico ha un valore poco plausibile.|Vuoi aggiornarlo secondo lo standard?.
        '''</summary>
        Friend Shared ReadOnly Property str00710() As String
            Get
                Return ResourceManager.GetString("str00710", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il valore impostato per il diametro esterno non è|abbastanza grande se confrontato con il diametro interno.
        '''</summary>
        Friend Shared ReadOnly Property str01000() As String
            Get
                Return ResourceManager.GetString("str01000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il valore impostato per il diametro esterno è eccessivo|se confrontato con il valore del diametro interno.
        '''</summary>
        Friend Shared ReadOnly Property str01001() As String
            Get
                Return ResourceManager.GetString("str01001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il valore impostato per il diametro interno è più piccolo
        '''di quello ottenuto sottraendo la sporgenza standard ({0:F} mm)
        '''dal diametro interno cassa  ({1:F} mm). Il valore impostato viene
        '''lasciato sotto la responsabilità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01002() As String
            Get
                Return ResourceManager.GetString("str01002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il valore impostato per il diametro interno è più grande
        '''di quello ottenuto sottraendo la sporgenza standard ({0:F} mm)
        '''dal diametro interno cassa  ({1:F} mm). Il valore impostato viene
        '''lasciato sotto la responsabilità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01003() As String
            Get
                Return ResourceManager.GetString("str01003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro interno massimo compatibile con l&apos;alloggiamento
        '''delle viti interne ed esterne è {0:F} mm. Tale valore tiene
        '''conto del cerchio viti intene, del diametro delle stesse, dello
        '''spessore dell&apos;anello di spinta e del cerchio delle viti superiori
        '''esterne.
        '''Il valore impostato è inferiore, e quindi la soluzione non è
        '''ottimale; esso viene lasciato sotto la responsabilità del
        '''progettista, fino al ripristino delle condizioni di calcolo
        '''automatico della geometria..
        '''</summary>
        Friend Shared ReadOnly Property str01004() As String
            Get
                Return ResourceManager.GetString("str01004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro interno massimo compatibile con l&apos;alloggiamento
        '''delle viti interne ed esterne è {0:F} mm. Tale valore tiene
        '''conto del cerchio viti intene, del diametro delle stesse, dello
        '''spessore dell&apos;anello di spinta e del cerchio delle viti superiori
        '''esterne.
        '''Il valore impostato è superiore, e quindi la soluzione rischia
        '''di non essere fattibile; esso viene lasciato sotto la responsa-
        '''bilità del progettista, fino al ripristino delle condizioni di calcolo
        '''automatico della geometria..
        '''</summary>
        Friend Shared ReadOnly Property str01005() As String
            Get
                Return ResourceManager.GetString("str01005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro esterno dell&apos;anello interno calcolato dal programma
        '''è {0:F} mm. Esso dipende dal tipo di cassonetto selezionato.
        '''Il valore impostato è inferiore, e viene lasciato sotto la respon-
        '''sabilità del progettista, fino al ripristino delle condizioni di calcolo
        '''automatico della geometria..
        '''</summary>
        Friend Shared ReadOnly Property str01006() As String
            Get
                Return ResourceManager.GetString("str01006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro esterno dell&apos;anello interno calcolato dal programma
        '''è {0:F} mm. Esso dipende dal tipo di cassonetto selezionato.
        '''Il valore impostato è superiore, e viene lasciato sotto la respon-
        '''sabilità del progettista, fino al ripristino delle condizioni di calcolo
        '''automatico della geometria..
        '''</summary>
        Friend Shared ReadOnly Property str01007() As String
            Get
                Return ResourceManager.GetString("str01007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;anello di spinta rischia di cadere all&apos;interno dell&apos;anello interno.
        '''</summary>
        Friend Shared ReadOnly Property str01008() As String
            Get
                Return ResourceManager.GetString("str01008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;anello di spinta rischia di interferire con le viti interne.
        '''</summary>
        Friend Shared ReadOnly Property str01009() As String
            Get
                Return ResourceManager.GetString("str01009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è stata definita l&apos;altezza del cassonetto.
        '''</summary>
        Friend Shared ReadOnly Property str01010() As String
            Get
                Return ResourceManager.GetString("str01010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro impostato è troppo piccolo.
        '''Esso viene lasciato sotto la responsabi-
        '''lità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01011() As String
            Get
                Return ResourceManager.GetString("str01011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro impostato è troppo grande.
        '''Esso viene lasciato sotto la responsabi-
        '''lità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01012() As String
            Get
                Return ResourceManager.GetString("str01012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro esterno della parte ativa della guarnizione è troppo piccolo.
        '''</summary>
        Friend Shared ReadOnly Property str01013() As String
            Get
                Return ResourceManager.GetString("str01013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro esterno della parte ativa della guarnizione potrebbe
        '''essere troppo grande.
        '''Infatti si crea gioco tra il diametro interno della guarnizione
        '''e il diametro interno del mantello.
        '''Può essere utile premere il pulsante &apos;Ricalcola lo standard&apos;..
        '''</summary>
        Friend Shared ReadOnly Property str01014() As String
            Get
                Return ResourceManager.GetString("str01014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La larghezza attiva della guarnizione è troppo grande.|Bisogna cambiare il diametro esterno della parte attiva| o la larghezza dell&apos;anello interno (se presente).
        '''Si suggerisce di premere il pulsante &apos;Ricalcola lo standard&apos;..
        '''</summary>
        Friend Shared ReadOnly Property str01015() As String
            Get
                Return ResourceManager.GetString("str01015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La larghezza attiva della guarnizione potrebbe essere troppo
        '''piccola. Infatti si crea gioco tra il diametro interno della guarni-
        '''zione e il diametro interno del mantello.
        '''Può essere utile premere il pulsante &apos;Ricalcola lo standard&apos;..
        '''</summary>
        Friend Shared ReadOnly Property str01016() As String
            Get
                Return ResourceManager.GetString("str01016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La larghezza dell&apos;anello interno è troppo grande.|Bisogna cambiare il diametro esterno della parte attiva| o la larghezza della parte attiva della guarnizione..
        '''</summary>
        Friend Shared ReadOnly Property str01017() As String
            Get
                Return ResourceManager.GetString("str01017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La larghezza dell&apos;anello interno potrebbe essere troppo
        '''piccola. Infatti si crea gioco tra il diametro interno della guarni-
        '''zione e il diametro interno del mantello.
        '''Può essere utile premere il pulsante &apos;Ricalcola lo standard&apos;..
        '''</summary>
        Friend Shared ReadOnly Property str01018() As String
            Get
                Return ResourceManager.GetString("str01018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;altezza del cassonetto non è definita.
        '''</summary>
        Friend Shared ReadOnly Property str01019() As String
            Get
                Return ResourceManager.GetString("str01019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il diametro interno della cassa è troppo piccolo.
        '''</summary>
        Friend Shared ReadOnly Property str01020() As String
            Get
                Return ResourceManager.GetString("str01020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Questo valore supera il valore massimo consigliato.
        '''Tuttavia il calcolo può continuare..
        '''</summary>
        Friend Shared ReadOnly Property str01021() As String
            Get
                Return ResourceManager.GetString("str01021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inserire la massima sporgenza attesa per l&apos;anello di spinta interno|rispetto alla faccia inferiore dell&apos;anello di blocco. Essa corrisponde|alle operazioni di serraggio in esercizio della guarnizione sotto la PT.|Il valore di default è pari a 3 mm..
        '''</summary>
        Friend Shared ReadOnly Property str01022() As String
            Get
                Return ResourceManager.GetString("str01022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inserire la massima sporgenza attesa per l&apos;anello di spinta esterno|rispetto alla faccia inferiore dell&apos;anello di blocco. Essa corrisponde|all&apos;operazione di serraggio della guarnizione sotto il diaframma.|Il valore di default è pari a 1 mm..
        '''</summary>
        Friend Shared ReadOnly Property str01023() As String
            Get
                Return ResourceManager.GetString("str01023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La spaziatura è inferiore al minimo consentito.
        '''Aumentare il diametro delle viti..
        '''</summary>
        Friend Shared ReadOnly Property str01024() As String
            Get
                Return ResourceManager.GetString("str01024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Questo valore è calcolato con fattore 1.3,
        '''tenendo conto del rapporto caldo/freddo
        '''degli ammissibili di pistra e tubi..
        '''</summary>
        Friend Shared ReadOnly Property str01025() As String
            Get
                Return ResourceManager.GetString("str01025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&apos; probabile che siano insorti problemi nell&apos;accesso
        '''alla libreria &apos;Brelb.ini&apos; per la variabile .
        '''</summary>
        Friend Shared ReadOnly Property str01026() As String
            Get
                Return ResourceManager.GetString("str01026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attendere la compilazione del rapporto.
        '''</summary>
        Friend Shared ReadOnly Property str01027() As String
            Get
                Return ResourceManager.GetString("str01027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Un calcolo precedente ha determinato lo spessore della parte liscia
        '''necessario per allineare i diametri esterni della parte liscia e della
        '''parte filettata.
        '''Lo spessore così determinato risulta ora eccessivo. 
        '''Volete riprendere in considerazione lo spessore minimo calcolato
        '''per la parte liscia?
        '''(Risposta raccomandata: Si).
        '''</summary>
        Friend Shared ReadOnly Property str01028() As String
            Get
                Return ResourceManager.GetString("str01028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è definita la pressione di progetto lato mantello.
        '''</summary>
        Friend Shared ReadOnly Property str01029() As String
            Get
                Return ResourceManager.GetString("str01029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è definita la temperatura di progetto lato mantello.
        '''</summary>
        Friend Shared ReadOnly Property str01030() As String
            Get
                Return ResourceManager.GetString("str01030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è definito il diametro interno del mantello.
        '''</summary>
        Friend Shared ReadOnly Property str01031() As String
            Get
                Return ResourceManager.GetString("str01031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è definito il raggio interno del fondo lato mantello.
        '''</summary>
        Friend Shared ReadOnly Property str01032() As String
            Get
                Return ResourceManager.GetString("str01032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è definito il diametro della guarnizione.
        '''</summary>
        Friend Shared ReadOnly Property str01033() As String
            Get
                Return ResourceManager.GetString("str01033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non sono definiti i parametri m e Y della guarnizione.
        '''</summary>
        Friend Shared ReadOnly Property str01034() As String
            Get
                Return ResourceManager.GetString("str01034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è definito il diametro del tubo scambiatore.
        '''</summary>
        Friend Shared ReadOnly Property str01035() As String
            Get
                Return ResourceManager.GetString("str01035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il passo della foratura è mal definito.
        '''</summary>
        Friend Shared ReadOnly Property str01036() As String
            Get
                Return ResourceManager.GetString("str01036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La pressione di prova idraulica lato mantello non è definita.
        '''Il calcolo automatico della stessa non è stato possibile
        '''poiché non è definita neppure la pressione differenziale
        '''di progetto lato mantello (vedi scheda &apos;Dati Generali&apos;)..
        '''</summary>
        Friend Shared ReadOnly Property str01037() As String
            Get
                Return ResourceManager.GetString("str01037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La pressione di prova idraulica differenziale lato mantello
        ''' non è definita..
        '''</summary>
        Friend Shared ReadOnly Property str01038() As String
            Get
                Return ResourceManager.GetString("str01038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La pressione di prova idraulica differenziale lato mantello
        '''è inferiore alla pressione differenziale di progetto molti-
        '''plicata per 1.3 e per il rapporto degli ammissibili.
        '''Vuoi mantenere il valore impostato?
        '''(Se rispondi di no il valore sarà ricalcolato
        '''automaticamente).
        '''</summary>
        Friend Shared ReadOnly Property str01039() As String
            Get
                Return ResourceManager.GetString("str01039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non essendo definita la pressione di progetto differenziale
        '''(vedi scheda Dati Generali) non è possibile calcolare lo
        '''spessore della piastra tubiera..
        '''</summary>
        Friend Shared ReadOnly Property str01040() As String
            Get
                Return ResourceManager.GetString("str01040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non è stato fornito il nome del file di dati.
        '''Accedere al menu Salva come ....
        '''</summary>
        Friend Shared ReadOnly Property str01041() As String
            Get
                Return ResourceManager.GetString("str01041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il valore impostato per lo spessore della flangia del
        '''cassonetto è inferiore allo spessore minimo di calcolo
        '''o allo spessore minimo standard.
        '''Il valore impostato viene lasciato sotto la responsabi-
        '''lità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01042() As String
            Get
                Return ResourceManager.GetString("str01042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alcune variabili geometriche (dimensioni, spessori) del problema
        '''sono state sottratte al procedimento di calcolo automatico.
        '''E&apos; quindi necessario prestare particolare attenzione ai risultati.
        '''Per ripristinare completamente l&apos;automatismo accedere al
        '''menu &apos;Azioni&apos;..
        '''</summary>
        Friend Shared ReadOnly Property str01043() As String
            Get
                Return ResourceManager.GetString("str01043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lo spessore impostato è inferiore allo spessore
        '''minimo di calcolo.
        '''Il valore impostato viene lasciato sotto la responsabi-
        '''lità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01044() As String
            Get
                Return ResourceManager.GetString("str01044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il cerchio viti massimo compatibile con il diametro interno
        '''della cassa è {0:F} mm. Il valore impostato è inferiore, e
        '''quindi la soluzione non è ottimale.
        '''Il valore impostato viene lasciato sotto la responsabi-
        '''lità del progettista fino al ripristino delle condizioni di
        '''calcolo automatico della geometria..
        '''</summary>
        Friend Shared ReadOnly Property str01045() As String
            Get
                Return ResourceManager.GetString("str01045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il cerchio viti massimo compatibile con il diametro interno
        '''della cassa è {0:F} mm. Il valore impostato è superiore, e
        '''quindi la soluzione non è fabbricabile.
        '''Il valore impostato viene lasciato sotto la responsabi-
        '''lità del progettista fino al ripristino delle condizioni di
        '''calcolo automatico della geometria..
        '''</summary>
        Friend Shared ReadOnly Property str01046() As String
            Get
                Return ResourceManager.GetString("str01046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&apos; stata scelta l&apos;opzione &apos;cassonetto cilindrico in linea&apos;.
        '''Il diametro di istallazione delle viti interne deve quindi
        '''essere uguale al diametro del cassonetto..
        '''</summary>
        Friend Shared ReadOnly Property str01047() As String
            Get
                Return ResourceManager.GetString("str01047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il valore impostato per il diametro della gola è più piccolo
        '''di quello ottenuto aggiungendo la spalla standard ({0:F} mm)
        '''al diametro fondo filetto  ({1:F} mm). Il valore impostato viene
        '''lasciato sotto la responsabilità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01048() As String
            Get
                Return ResourceManager.GetString("str01048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Il valore impostato per il diametro della gola è più grande
        '''di quello ottenuto aggiungendo la spalla standard ({0:F} mm)
        '''al diametro fondo filetto  ({1:F} mm). Il valore impostato viene
        '''lasciato sotto la responsabilità del progettista.
        '''(Vedi colore rosa di sfondo della casella di testo).
        '''</summary>
        Friend Shared ReadOnly Property str01049() As String
            Get
                Return ResourceManager.GetString("str01049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Questo valore può essere lasciato in bianco. In tal caso esso|verrà calcolato a partire dalla pressione differenziale di progetto|già specificata.
        '''</summary>
        Friend Shared ReadOnly Property str09001() As String
            Get
                Return ResourceManager.GetString("str09001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Condizione di carico dimensionante:.
        '''</summary>
        Friend Shared ReadOnly Property str09002() As String
            Get
                Return ResourceManager.GetString("str09002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Design.
        '''</summary>
        Friend Shared ReadOnly Property str09003() As String
            Get
                Return ResourceManager.GetString("str09003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seating.
        '''</summary>
        Friend Shared ReadOnly Property str09004() As String
            Get
                Return ResourceManager.GetString("str09004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prova idraulica (parte filettata).
        '''</summary>
        Friend Shared ReadOnly Property str09005() As String
            Get
                Return ResourceManager.GetString("str09005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prova idraulica (estensione).
        '''</summary>
        Friend Shared ReadOnly Property str09006() As String
            Get
                Return ResourceManager.GetString("str09006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&apos; opportuno scegliere come valore della sezione retta dell&apos;estensione il valore minimo al di sopra del quale la condizione dimensionante non sia &apos;Prova idraulica (estensione)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property str09007() As String
            Get
                Return ResourceManager.GetString("str09007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se si sceglie l&apos;opzione monolaterale la pressione differenziale agirà in con-
        '''dizioni di progetto solo dal lato tubi. Essa sarà quindi dimensionante per
        '''la piastra tubiera, ma non per il sistema di compressione della guarnizione
        '''sotto di essa. La pressione differenziale di prova idraulica lato mantello
        '''viene specificata nella scheda &apos;Piastra tubiera&apos;.
        '''Se si sceglie l&apos;opzione bilaterale, la pressione differenziale di progetto agi-
        '''rà su entrambi i lati, e la pressione differenziale di prova idraulica p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property str09008() As String
            Get
                Return ResourceManager.GetString("str09008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tensioni elevate o rischio di buckling: aumentare lo spessore..
        '''</summary>
        Friend Shared ReadOnly Property str09009() As String
            Get
                Return ResourceManager.GetString("str09009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Design: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09010() As String
            Get
                Return ResourceManager.GetString("str09010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seating: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09011() As String
            Get
                Return ResourceManager.GetString("str09011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09012() As String
            Get
                Return ResourceManager.GetString("str09012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Design: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09013() As String
            Get
                Return ResourceManager.GetString("str09013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seating: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09014() As String
            Get
                Return ResourceManager.GetString("str09014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09015() As String
            Get
                Return ResourceManager.GetString("str09015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bearing stress elevato sugli inserti sotto le viti interne:.
        '''</summary>
        Friend Shared ReadOnly Property str09016() As String
            Get
                Return ResourceManager.GetString("str09016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Design: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09017() As String
            Get
                Return ResourceManager.GetString("str09017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seating: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09018() As String
            Get
                Return ResourceManager.GetString("str09018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test: {0,8:F} &gt; {1,8:F}.
        '''</summary>
        Friend Shared ReadOnly Property str09019() As String
            Get
                Return ResourceManager.GetString("str09019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&apos; probabilmente necessario cambiare il materiale
        '''con uno a più alto snervamento..
        '''</summary>
        Friend Shared ReadOnly Property str09020() As String
            Get
                Return ResourceManager.GetString("str09020", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
