<Project>
  <ItemGroup Condition="'$(UseWindowsForms)' == 'true' And '$(GenerateAssemblyInfo)' == 'false'">
    <Compile Include="$(MSBuildThisFileDirectory)Migration/LegacyWindowsPlatform.vb" Link="Migration/LegacyWindowsPlatform.vb" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseWindowsForms)' == 'true'">
    <Compile Include="$(MSBuildThisFileDirectory)Migration/LegacyStatusLabel.vb" Link="Migration/LegacyStatusLabel.vb" />
    <Compile Include="$(MSBuildThisFileDirectory)Migration/LegacyGridView.vb" Link="Migration/LegacyGridView.vb" />
  </ItemGroup>
</Project>
