;Normative di calcolo della forza dovuta al sisma
;Nell'introdurre nuove norme o variazioni i simboli F e Wp devono restare
[not applicable] 
[ASCE 7 1995 Ed.]
F=0.4*Ca*Ip*Wp,N,formula
Ca=Soil Factor,--,0.34
Ip=Importance Factor,--,1.5
Wp=Horizontal Force,N,1
Formula={\rtf1\ansi F=0.4{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}C{\sub a}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}I{\sub p}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}W{\sub p}}
[UBC-94, Chapter 16]
F=Z*I*Cp*Wp,N,formula
Z=acceleration Factor,--,0.3
I=Importance Factor,--,1.5
Cp=Soil Factor,--,0.75
Wp=Horizontal Force,N,1
Formula={\rtf1\ansi F=Z{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}I{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}C{\sub p}{\field{\*\fldinst SYMBOL 215 \\f "Symbol" \\s}}W{\sub p}}
