'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:2.0.50727.42
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.ComponentModel.ToolboxItem(true),  _
 System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 System.Xml.Serialization.XmlRootAttribute("dsCommesse"),  _
 System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsCommesse
    Inherits System.Data.DataSet
    
    Private tableAutorizz As AutorizzDataTable
    
    Private _schemaSerializationMode As System.Data.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Autorizz")) Is Nothing) Then
                MyBase.Tables.Add(New AutorizzDataTable(ds.Tables("Autorizz")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Autorizz() As AutorizzDataTable
        Get
            Return Me.tableAutorizz
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.BrowsableAttribute(true),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As System.Data.DataSet
        Dim cln As dsCommesse = CType(MyBase.Clone,dsCommesse)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("Autorizz")) Is Nothing) Then
                MyBase.Tables.Add(New AutorizzDataTable(ds.Tables("Autorizz")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableAutorizz = CType(MyBase.Tables("Autorizz"),AutorizzDataTable)
        If (initTable = true) Then
            If (Not (Me.tableAutorizz) Is Nothing) Then
                Me.tableAutorizz.InitVars
            End If
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "dsCommesse"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsCommesse.xsd"
        Me.Locale = New System.Globalization.CultureInfo("it-IT")
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableAutorizz = New AutorizzDataTable
        MyBase.Tables.Add(Me.tableAutorizz)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeAutorizz() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsCommesse = New dsCommesse
        Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
        xs.Add(ds.GetSchemaSerializable)
        Dim any As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Return type
    End Function
    
    Public Delegate Sub AutorizzRowChangeEventHandler(ByVal sender As Object, ByVal e As AutorizzRowChangeEvent)
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.Serializable(),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class AutorizzDataTable
        Inherits System.Data.DataTable
        Implements System.Collections.IEnumerable
        
        Private columnID As System.Data.DataColumn
        
        Private columnOperazione As System.Data.DataColumn
        
        Private columnQualif1 As System.Data.DataColumn
        
        Private columnQualif2 As System.Data.DataColumn
        
        Private columnQualif3 As System.Data.DataColumn
        
        Private columnQualif4 As System.Data.DataColumn
        
        Private columnQualif5 As System.Data.DataColumn
        
        Private columnQualif6 As System.Data.DataColumn
        
        Private columnQualif7 As System.Data.DataColumn
        
        Private columnQualif8 As System.Data.DataColumn
        
        Private columnQualif9 As System.Data.DataColumn
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "Autorizz"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property IDColumn() As System.Data.DataColumn
            Get
                Return Me.columnID
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property OperazioneColumn() As System.Data.DataColumn
            Get
                Return Me.columnOperazione
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif1Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif1
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif2Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif2
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif3Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif3
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif4Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif4
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif5Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif5
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif6Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif6
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif7Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif7
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif8Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif8
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qualif9Column() As System.Data.DataColumn
            Get
                Return Me.columnQualif9
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As AutorizzRow
            Get
                Return CType(Me.Rows(index),AutorizzRow)
            End Get
        End Property
        
        Public Event AutorizzRowChanging As AutorizzRowChangeEventHandler
        
        Public Event AutorizzRowChanged As AutorizzRowChangeEventHandler
        
        Public Event AutorizzRowDeleting As AutorizzRowChangeEventHandler
        
        Public Event AutorizzRowDeleted As AutorizzRowChangeEventHandler
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddAutorizzRow(ByVal row As AutorizzRow)
            Me.Rows.Add(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddAutorizzRow(ByVal Operazione As String, ByVal Qualif1 As String, ByVal Qualif2 As String, ByVal Qualif3 As String, ByVal Qualif4 As String, ByVal Qualif5 As String, ByVal Qualif6 As String, ByVal Qualif7 As String, ByVal Qualif8 As String, ByVal Qualif9 As String) As AutorizzRow
            Dim rowAutorizzRow As AutorizzRow = CType(Me.NewRow,AutorizzRow)
            rowAutorizzRow.ItemArray = New Object() {Nothing, Operazione, Qualif1, Qualif2, Qualif3, Qualif4, Qualif5, Qualif6, Qualif7, Qualif8, Qualif9}
            Me.Rows.Add(rowAutorizzRow)
            Return rowAutorizzRow
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByID(ByVal ID As Integer) As AutorizzRow
            Return CType(Me.Rows.Find(New Object() {ID}),AutorizzRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As System.Data.DataTable
            Dim cln As AutorizzDataTable = CType(MyBase.Clone,AutorizzDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As System.Data.DataTable
            Return New AutorizzDataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnID = MyBase.Columns("ID")
            Me.columnOperazione = MyBase.Columns("Operazione")
            Me.columnQualif1 = MyBase.Columns("Qualif1")
            Me.columnQualif2 = MyBase.Columns("Qualif2")
            Me.columnQualif3 = MyBase.Columns("Qualif3")
            Me.columnQualif4 = MyBase.Columns("Qualif4")
            Me.columnQualif5 = MyBase.Columns("Qualif5")
            Me.columnQualif6 = MyBase.Columns("Qualif6")
            Me.columnQualif7 = MyBase.Columns("Qualif7")
            Me.columnQualif8 = MyBase.Columns("Qualif8")
            Me.columnQualif9 = MyBase.Columns("Qualif9")
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnID = New System.Data.DataColumn("ID", GetType(Integer), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID)
            Me.columnOperazione = New System.Data.DataColumn("Operazione", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOperazione)
            Me.columnQualif1 = New System.Data.DataColumn("Qualif1", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif1)
            Me.columnQualif2 = New System.Data.DataColumn("Qualif2", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif2)
            Me.columnQualif3 = New System.Data.DataColumn("Qualif3", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif3)
            Me.columnQualif4 = New System.Data.DataColumn("Qualif4", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif4)
            Me.columnQualif5 = New System.Data.DataColumn("Qualif5", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif5)
            Me.columnQualif6 = New System.Data.DataColumn("Qualif6", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif6)
            Me.columnQualif7 = New System.Data.DataColumn("Qualif7", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif7)
            Me.columnQualif8 = New System.Data.DataColumn("Qualif8", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif8)
            Me.columnQualif9 = New System.Data.DataColumn("Qualif9", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQualif9)
            Me.Constraints.Add(New System.Data.UniqueConstraint("Constraint1", New System.Data.DataColumn() {Me.columnID}, true))
            Me.columnID.AutoIncrement = true
            Me.columnID.AllowDBNull = false
            Me.columnID.Unique = true
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewAutorizzRow() As AutorizzRow
            Return CType(Me.NewRow,AutorizzRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As System.Data.DataRowBuilder) As System.Data.DataRow
            Return New AutorizzRow(builder)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(AutorizzRow)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.AutorizzRowChangedEvent) Is Nothing) Then
                RaiseEvent AutorizzRowChanged(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.AutorizzRowChangingEvent) Is Nothing) Then
                RaiseEvent AutorizzRowChanging(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.AutorizzRowDeletedEvent) Is Nothing) Then
                RaiseEvent AutorizzRowDeleted(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.AutorizzRowDeletingEvent) Is Nothing) Then
                RaiseEvent AutorizzRowDeleting(Me, New AutorizzRowChangeEvent(CType(e.Row,AutorizzRow), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveAutorizzRow(ByVal row As AutorizzRow)
            Me.Rows.Remove(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
            Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
            Dim ds As dsCommesse = New dsCommesse
            xs.Add(ds.GetSchemaSerializable)
            Dim any1 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "AutorizzDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Return type
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class AutorizzRow
        Inherits System.Data.DataRow
        
        Private tableAutorizz As AutorizzDataTable
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableAutorizz = CType(Me.Table,AutorizzDataTable)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ID() As Integer
            Get
                Return CType(Me(Me.tableAutorizz.IDColumn),Integer)
            End Get
            Set
                Me(Me.tableAutorizz.IDColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Operazione() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.OperazioneColumn),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Operazione' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.OperazioneColumn) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif1() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif1Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif1' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif1Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif2() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif2Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif2' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif2Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif3() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif3Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif3' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif3Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif4() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif4Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif4' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif4Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif5() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif5Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif5' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif5Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif6() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif6Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif6' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif6Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif7() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif7Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif7' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif7Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif8() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif8Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif8' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif8Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qualif9() As String
            Get
                Try 
                    Return CType(Me(Me.tableAutorizz.Qualif9Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("Il valore della colonna 'Qualif9' nella tabella 'Autorizz' è DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableAutorizz.Qualif9Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsOperazioneNull() As Boolean
            Return Me.IsNull(Me.tableAutorizz.OperazioneColumn)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetOperazioneNull()
            Me(Me.tableAutorizz.OperazioneColumn) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif1Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif1Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif1Null()
            Me(Me.tableAutorizz.Qualif1Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif2Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif2Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif2Null()
            Me(Me.tableAutorizz.Qualif2Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif3Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif3Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif3Null()
            Me(Me.tableAutorizz.Qualif3Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif4Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif4Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif4Null()
            Me(Me.tableAutorizz.Qualif4Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif5Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif5Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif5Null()
            Me(Me.tableAutorizz.Qualif5Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif6Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif6Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif6Null()
            Me(Me.tableAutorizz.Qualif6Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif7Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif7Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif7Null()
            Me(Me.tableAutorizz.Qualif7Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif8Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif8Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif8Null()
            Me(Me.tableAutorizz.Qualif8Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQualif9Null() As Boolean
            Return Me.IsNull(Me.tableAutorizz.Qualif9Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQualif9Null()
            Me(Me.tableAutorizz.Qualif9Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class AutorizzRowChangeEvent
        Inherits System.EventArgs
        
        Private eventRow As AutorizzRow
        
        Private eventAction As System.Data.DataRowAction
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As AutorizzRow, ByVal action As System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As AutorizzRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
